// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ReLiveWP.Backend.ConnectedServices.Data;

#nullable disable

namespace ReLiveWP.Backend.ConnectedServices.Migrations
{
    [DbContext(typeof(ConnectedServicesDbContext))]
    [Migration("20260808075958_ConnectionLabel")]
    partial class ConnectionLabel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ReLiveWP.Backend.ConnectedServices.Data.LiveConnectedService", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AuthorizationEndpoint")
                        .HasColumnType("text");

                    b.Property<long>("AvailableCapabilities")
                        .HasColumnType("bigint");

                    b.Property<string>("DPoPKeyId")
                        .HasColumnType("text");

                    b.Property<long>("EnabledCapabilities")
                        .HasColumnType("bigint");

                    b.Property<string>("EncryptedSecret")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Flags")
                        .HasColumnType("bigint");

                    b.Property<string>("Issuer")
                        .HasColumnType("text");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<string>("Service")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ServiceUrl")
                        .HasColumnType("text");

                    b.Property<string>("TokenEndpoint")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DPoPKeyId");

                    b.ToTable("ConnectedServices");
                });

            modelBuilder.Entity("ReLiveWP.Backend.ConnectedServices.Data.LiveDPoPKey", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DPoPKeys");
                });

            modelBuilder.Entity("ReLiveWP.Backend.ConnectedServices.Data.LiveConnectedService", b =>
                {
                    b.HasOne("ReLiveWP.Backend.ConnectedServices.Data.LiveDPoPKey", "DPoPKey")
                        .WithMany()
                        .HasForeignKey("DPoPKeyId");

                    b.OwnsOne("ReLiveWP.Backend.ConnectedServices.Data.LiveConnectedServiceProfile", "ServiceProfile", b1 =>
                        {
                            b1.Property<Guid>("LiveConnectedServiceId")
                                .HasColumnType("uuid");

                            b1.Property<string>("AvatarUrl")
                                .HasColumnType("text");

                            b1.Property<string>("DisplayName")
                                .HasColumnType("text");

                            b1.Property<string>("EmailAddress")
                                .HasColumnType("text");

                            b1.Property<string>("Label")
                                .HasColumnType("text");

                            b1.Property<string>("UserId")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Username")
                                .HasColumnType("text");

                            b1.HasKey("LiveConnectedServiceId");

                            b1.ToTable("ConnectedServices");

                            b1.WithOwner()
                                .HasForeignKey("LiveConnectedServiceId");
                        });

                    b.Navigation("DPoPKey");

                    b.Navigation("ServiceProfile")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
