// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReLiveWP.Backend.ConnectedServices.Data;

#nullable disable

namespace ReLiveWP.Backend.ConnectedServices.Migrations
{
    [DbContext(typeof(ConnectedServicesDbContext))]
    [Migration("20260628202056_AvailableCapabilities")]
    partial class AvailableCapabilities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.16");

            modelBuilder.Entity("ReLiveWP.Backend.ConnectedServices.Data.LiveConnectedService", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AuthorizationEndpoint")
                        .HasColumnType("TEXT");

                    b.Property<uint>("AvailableCapabilities")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DPoPKeyId")
                        .HasColumnType("TEXT");

                    b.Property<uint>("EnabledCapabilities")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<uint>("Flags")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Issuer")
                        .HasColumnType("TEXT");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Service")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ServiceUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("TokenEndpoint")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DPoPKeyId");

                    b.ToTable("ConnectedServices");
                });

            modelBuilder.Entity("ReLiveWP.Backend.ConnectedServices.Data.LiveDPoPKey", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DPoPKeys");
                });

            modelBuilder.Entity("ReLiveWP.Backend.ConnectedServices.Data.LivePendingOAuth", b =>
                {
                    b.Property<string>("State")
                        .HasColumnType("TEXT");

                    b.Property<string>("AuthorizationEndpoint")
                        .HasColumnType("TEXT");

                    b.Property<string>("CodeVerifier")
                        .HasColumnType("TEXT");

                    b.Property<string>("Endpoint")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ExistingConnectionId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Service")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TokenEndpoint")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("State");

                    b.HasIndex("State");

                    b.ToTable("PendingOAuths");
                });

            modelBuilder.Entity("ReLiveWP.Backend.ConnectedServices.Data.LiveConnectedService", b =>
                {
                    b.HasOne("ReLiveWP.Backend.ConnectedServices.Data.LiveDPoPKey", "DPoPKey")
                        .WithMany()
                        .HasForeignKey("DPoPKeyId");

                    b.OwnsOne("ReLiveWP.Backend.ConnectedServices.Data.LiveConnectedServiceProfile", "ServiceProfile", b1 =>
                        {
                            b1.Property<Guid>("LiveConnectedServiceId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("AvatarUrl")
                                .HasColumnType("TEXT");

                            b1.Property<string>("DisplayName")
                                .HasColumnType("TEXT");

                            b1.Property<string>("EmailAddress")
                                .HasColumnType("TEXT");

                            b1.Property<string>("UserId")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Username")
                                .HasColumnType("TEXT");

                            b1.HasKey("LiveConnectedServiceId");

                            b1.ToTable("ConnectedServices");

                            b1.WithOwner()
                                .HasForeignKey("LiveConnectedServiceId");
                        });

                    b.Navigation("DPoPKey");

                    b.Navigation("ServiceProfile")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
