<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <UserSecretsId>6cc4b98e-30b7-4216-85cd-65ac619f665a</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <SsoStyleDir>$(MSBuildProjectDirectory)/../ReLiveWP.Web/relivewp.web.sso</SsoStyleDir>
    <UiPackageDir>$(SsoStyleDir)/node_modules/@relivewp/ui</UiPackageDir>
    <SsoStylesheet>$(MSBuildProjectDirectory)/wwwroot/sso/login.css</SsoStylesheet>
    <PnpmInstall Condition="'$(OS)' == 'Windows_NT'">pnpm install --silent || (ping -n 11 127.0.0.1 &gt;nul &amp; pnpm install --silent)</PnpmInstall>
    <PnpmInstall Condition="'$(OS)' != 'Windows_NT'">pnpm install --silent || (sleep 10; pnpm install --silent)</PnpmInstall>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" />
    <PackageReference Include="Google.Protobuf" />
    <PackageReference Include="Grpc.Net.Client" />
    <PackageReference Include="Grpc.Net.ClientFactory" />
    <PackageReference Include="Grpc.Tools">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.AspNetCore.DataProtection.StackExchangeRedis" />
    <PackageReference Include="Razor.Templating.Core" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ReLiveWP.Identity\ReLiveWP.Identity.csproj" />
    <ProjectReference Include="..\ReLiveWP.Passport\ReLiveWP.Passport.csproj" />
    <ProjectReference Include="..\ReLiveWP.ServiceDefaults\ReLiveWP.ServiceDefaults.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Protobuf Include="../protos/authentication.proto" GrpcServices="Client">
      <Link>Protos\authentication.proto</Link>
    </Protobuf>
    <Protobuf Include="../protos/oauth.proto" GrpcServices="Client">
      <Link>Protos\oauth.proto</Link>
    </Protobuf>
    <Protobuf Include="../protos/user.proto" GrpcServices="Client">
      <Link>Protos\user.proto</Link>
    </Protobuf>
    <Protobuf Include="../protos/device_registration.proto" GrpcServices="Client">
      <Link>Protos\device_registration.proto</Link>
    </Protobuf>
    <Protobuf Include="../protos/client_provisioning.proto" GrpcServices="Client">
      <Link>Protos\client_provisioning.proto</Link>
    </Protobuf>
    <Protobuf Include="../protos/sso.proto" GrpcServices="Client">
      <Link>Protos\sso.proto</Link>
    </Protobuf>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Utilities\" />
  </ItemGroup>

  <ItemGroup>
    <SassInput Include="$(SsoStyleDir)/Styles/**/*.scss" />
    <SassInput Include="$(UiPackageDir)/styles/**/*.scss" />
  </ItemGroup>

  <Target Name="RestoreStyleTools"
          Inputs="$(SsoStyleDir)/package.json;$(MSBuildProjectDirectory)/../ReLiveWP.Web/pnpm-lock.yaml"
          Outputs="$(SsoStyleDir)/node_modules/.modules.yaml">
    <Exec Command="$(PnpmInstall)" WorkingDirectory="$(SsoStyleDir)" />
  </Target>

  <Target Name="BuildLoginStyles"
          DependsOnTargets="RestoreStyleTools"
          Inputs="@(SassInput)"
          Outputs="$(SsoStylesheet)">
    <Exec Command="pnpm run styles" WorkingDirectory="$(SsoStyleDir)" />
  </Target>

  <Target Name="IncludeLoginStyles"
          DependsOnTargets="BuildLoginStyles"
          BeforeTargets="AssignTargetPaths">
    <ItemGroup>
      <Content Include="$(SsoStylesheet)" CopyToPublishDirectory="PreserveNewest" />
    </ItemGroup>
  </Target>

</Project>
