<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <PackageReference Include="Google.Protobuf" />
    <PackageReference Include="Grpc.Net.Client" />
    <PackageReference Include="Grpc.Net.ClientFactory" />
    <PackageReference Include="Grpc.Tools">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <Protobuf Include="../protos/find_my_phone.proto" GrpcServices="Client">
      <Link>Protos\find_my_phone.proto</Link>
    </Protobuf>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ReLiveWP.Identity\ReLiveWP.Identity.csproj" />
  </ItemGroup>

</Project>
