<Project>
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <OutputPath>$(MSBuildThisFileDirectory)bin\$(Configuration)\$(MSBuildProjectName)</OutputPath>
    <PublishDir>$(MSBuildThisFileDirectory)publish\$(TargetFramework)\$(RuntimeIdentifier)\$(MSBuildProjectName)</PublishDir>
    <IsPublishable Condition="$(MSBuildProjectName.EndsWith('.Tests'))">false</IsPublishable>
  </PropertyGroup>
</Project>
