<Project>
  <PropertyGroup>
    <TargetFramework>net11.0</TargetFramework>
    <Features>runtime-async=on</Features>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseArtifactsOutput>true</UseArtifactsOutput>
    <IsPublishable Condition="$(MSBuildProjectName.EndsWith('.Tests'))">false</IsPublishable>
  </PropertyGroup>
</Project>