services:
  identity:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PROJECT: ReLiveWP.Backend.Identity

  connectedservices:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PROJECT: ReLiveWP.Backend.ConnectedServices

  deviceregistration:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PROJECT: ReLiveWP.Backend.DeviceRegistration

  skybox:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PROJECT: ReLiveWP.Backend.Skybox

  activation:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PROJECT: ReLiveWP.Services.Activation

  login:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PROJECT: ReLiveWP.Services.Login

  zunecommerce:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PROJECT: ReLiveWP.Zune.Commerce

  web:
    build:
      context: .
      dockerfile: ReLiveWP.Web/ReLiveWP.Web.Server/Dockerfile

  push:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PROJECT: ReLiveWP.Services.Push

  zunecatalog:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PROJECT: ReLiveWP.Zune.Catalog

  activity:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PROJECT: ReLiveWP.Services.Activity

  exchange:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PROJECT: ReLiveWP.Services.Exchange

  addressbook:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PROJECT: ReLiveWP.Services.AddressBook

  devices:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PROJECT: ReLiveWP.Services.Devices

  findmyphone:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PROJECT: ReLiveWP.Services.FindMyPhone

  orion:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PROJECT: ReLiveWP.Services.Orion