---
name: relivewp

services:
  identity:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PROJECT: ReLiveWP.Backend.Identity

  connectedservices:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PROJECT: ReLiveWP.Backend.ConnectedServices

  deviceregistration:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PROJECT: ReLiveWP.Backend.DeviceRegistration

  skybox:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PROJECT: ReLiveWP.Backend.Skybox

  skydrive:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PROJECT: ReLiveWP.Backend.SkyDrive

  activation:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PROJECT: ReLiveWP.Services.Activation

  login:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PROJECT: ReLiveWP.Services.Login

  web:
    build:
      context: .
      dockerfile: ReLiveWP.Web/Dockerfile

  push:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PROJECT: ReLiveWP.Services.Push

  activity:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PROJECT: ReLiveWP.Services.Activity

  exchange:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PROJECT: ReLiveWP.Services.Exchange

  addressbook:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PROJECT: ReLiveWP.Services.AddressBook

  devices:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PROJECT: ReLiveWP.Services.Devices

  findmyphone:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PROJECT: ReLiveWP.Services.FindMyPhone

  orion:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PROJECT: ReLiveWP.Services.Orion
        