<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <PackageReference Include="SoapCore" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\libraries\ReLiveWP.Grpc.Services\ReLiveWP.Grpc.Services.csproj" />
    <ProjectReference Include="..\..\libraries\ReLiveWP.Identity\ReLiveWP.Identity.csproj" />
    <ProjectReference Include="..\..\libraries\ReLiveWP.ServiceDefaults\ReLiveWP.ServiceDefaults.csproj" />
  </ItemGroup>

</Project>
