// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ReLiveWP.Services.Push.Data;

#nullable disable

namespace ReLiveWP.Services.Push.Migrations
{
    [DbContext(typeof(PushDatabase))]
    partial class PushDatabaseModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ReLiveWP.Services.Push.Data.DeviceSession", b =>
                {
                    b.Property<string>("Token")
                        .HasColumnType("text");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("bigint");

                    b.Property<string>("DeviceId")
                        .HasColumnType("text");

                    b.Property<long>("LastSeenAt")
                        .HasColumnType("bigint");

                    b.HasKey("Token");

                    b.HasIndex("DeviceId");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("ReLiveWP.Services.Push.Data.PushChannel", b =>
                {
                    b.Property<long>("ChannelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ChannelId"));

                    b.Property<string>("ChannelName")
                        .HasColumnType("text");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("bigint");

                    b.Property<string>("DeviceId")
                        .HasColumnType("text");

                    b.Property<string>("Identifier")
                        .HasColumnType("text");

                    b.Property<string>("ServiceName")
                        .HasColumnType("text");

                    b.Property<string>("Token")
                        .HasColumnType("text");

                    b.Property<string>("Version")
                        .HasColumnType("text");

                    b.HasKey("ChannelId");

                    b.HasIndex("DeviceId");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.ToTable("Channels");
                });

            modelBuilder.Entity("ReLiveWP.Services.Push.Data.QueuedNotification", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<long>("ChannelId")
                        .HasColumnType("bigint");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("bigint");

                    b.Property<string>("DeviceId")
                        .HasColumnType("text");

                    b.Property<long?>("ExpiresAt")
                        .HasColumnType("bigint");

                    b.Property<string>("LastError")
                        .HasColumnType("text");

                    b.Property<long?>("LeaseExpiresAt")
                        .HasColumnType("bigint");

                    b.Property<string>("LeaseOwner")
                        .HasColumnType("text");

                    b.Property<long>("NotificationClass")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("Payload")
                        .HasColumnType("bytea");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("DeviceId", "Status");

                    b.HasIndex("Status", "LeaseExpiresAt");

                    b.ToTable("Notifications");
                });
#pragma warning restore 612, 618
        }
    }
}
