events {}

http {
  map $request_method $cors_method {
    OPTIONS 204;
    default 0;
  }

  server {
    listen 80;
    server_name login.int.relivewp.net;
    location / {
      if ($request_method = OPTIONS) {
        add_header Access-Control-Allow-Origin *;
        add_header Access-Control-Allow-Methods "GET, POST, PUT, PATCH, DELETE, OPTIONS";
        add_header Access-Control-Allow-Headers "Authorization, Content-Type";
        return 204;
      }
      add_header Access-Control-Allow-Origin *;
      proxy_pass http://login:10002;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }
  }

  server {
    listen 80;
    server_name devices.int.relivewp.net;
    location / {
      if ($request_method = OPTIONS) {
        add_header Access-Control-Allow-Origin *;
        add_header Access-Control-Allow-Methods "GET, POST, PUT, PATCH, DELETE, OPTIONS";
        add_header Access-Control-Allow-Headers "Authorization, Content-Type";
        return 204;
      }
      add_header Access-Control-Allow-Origin *;
      proxy_pass http://devices:10011;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }
  }

  server {
    listen 80;
    server_name api.live.int.relivewp.net;
    
    # increase the maximum size for images
    client_max_body_size 32m;
    proxy_request_buffering off;
    proxy_read_timeout 300s;
    location / {
      proxy_pass http://activity:10007;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }
  }

  server {
    listen 80;
    server_name services.int.relivewp.net;
    location / {
      proxy_pass http://findmyphone:10012;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }
  }

  server {
    listen 80;
    server_name push.int.relivewp.net;
    location / {
      proxy_pass http://push:10005;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }
  }

  server {
    listen 80;
    server_name int.relivewp.net;
    location / {
      proxy_pass http://web:8080;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }
  }
}
