// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ReLiveWP.Backend.DeviceRegistration.Data;

#nullable disable

namespace ReLiveWP.Backend.DeviceRegistration.Migrations
{
    [DbContext(typeof(DevicesDbContext))]
    [Migration("20260922215817_ActivationCodeRedemptions")]
    partial class ActivationCodeRedemptions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ReLiveWP.Backend.DeviceRegistration.Model.ActivationCodeRedemption", b =>
                {
                    b.Property<int>("Serial")
                        .HasColumnType("integer");

                    b.Property<string>("ActivationCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DeviceUniqueId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("RedeemedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Serial");

                    b.ToTable("ActivationCodeRedemptions");
                });

            modelBuilder.Entity("ReLiveWP.Backend.DeviceRegistration.Model.DeviceModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("CertificateSubject")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IMEI")
                        .HasColumnType("text");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("text");

                    b.Property<string>("Model")
                        .HasColumnType("text");

                    b.Property<string>("OSVersion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Operator")
                        .HasColumnType("text");

                    b.Property<string>("OwnerId")
                        .HasColumnType("text");

                    b.Property<string>("UniqueId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CertificateSubject");

                    b.HasIndex("UniqueId");

                    b.ToTable("Devices");
                });
#pragma warning restore 612, 618
        }
    }
}
