<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <UserSecretsId>f6c3debc-710f-417e-87f7-3101a669fe24</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Grpc.AspNetCore" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" />
    <PackageReference Include="Portable.BouncyCastle" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\libraries\ReLiveWP.Identity\ReLiveWP.Identity.csproj" />
    <ProjectReference Include="..\..\libraries\ReLiveWP.Passport\ReLiveWP.Passport.csproj" />
    <ProjectReference Include="..\..\libraries\ReLiveWP.ProductKeys\ReLiveWP.ProductKeys.csproj" />
    <ProjectReference Include="..\..\libraries\ReLiveWP.ServiceDefaults\ReLiveWP.ServiceDefaults.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Protobuf Include="$(RepoRoot)protos/authentication.proto" GrpcServices="Server">
      <Link>Protos\authentication.proto</Link>
    </Protobuf>
    <Protobuf Include="$(RepoRoot)protos/user.proto" GrpcServices="Server">
      <Link>Protos\user.proto</Link>
    </Protobuf>
    <Protobuf Include="$(RepoRoot)protos/sso.proto" GrpcServices="Server">
      <Link>Protos\sso.proto</Link>
    </Protobuf>
  </ItemGroup>

</Project>
