[Kestrel:Endpoints:Https]
Url=http://0.0.0.0:5000

[Kestrel:EndpointDefaults]
Protocols=Http2

; ConnectionStrings:DefaultConnection is supplied via the ConnectionStrings__DefaultConnection docker secret

[CertificateGeneration]
RootCACertFile=/certs/provisioning_ca.pfx
