[Kestrel:Endpoints:Https]
Url=http://0.0.0.0:5000
Protocols=Http2

[Kestrel:Endpoints:Https2]
Url=http://0.0.0.0:5001
Protocols=Http1

; ConnectionStrings:DefaultConnection is supplied via the ConnectionStrings__DefaultConnection docker secret

[CertificateGeneration]
CACertFile=/certs/identity_ca.pfx
RootCACertFile=/certs/root_ca.pfx
