syntax = "proto3";
import "google/protobuf/empty.proto";
import "google/protobuf/timestamp.proto";

option csharp_namespace = "ReLiveWP.Services.Grpc";

package identity;

service ConnectedServices {
  rpc GetJsonWebKeys(google.protobuf.Empty) returns (JsonWebKeysResponse);

  rpc BeginAccountLinkingForService(BeginAccountLinkingRequest) returns (BeginAccountLinkingResponse);
  rpc FinaliseAccountLinkingForService(FinaliseAccountLinkingRequest) returns (FinaliseAccountLinkingResponse);

  rpc BeginRelinkForConnection(BeginRelinkRequest) returns (BeginAccountLinkingResponse);

  rpc DeleteConnection(DeleteConnectionRequest) returns (DeleteConnectionResponse);

  rpc GetSupportedConnections(google.protobuf.Empty) returns (SupportedConnectionsResponse);
  rpc GetConnections(ConnectionsRequest) returns (stream Connection);

  rpc UpdateCapabilities(UpdateCapabilitiesRequest) returns (google.protobuf.Empty);
}

message JsonWebKeysResponse {
	string keys = 1;
}

message BeginAccountLinkingRequest {
	string service = 1;
	string identifer = 2;
}

message BeginRelinkRequest {
	string connectionId = 1;
}

message BeginAccountLinkingResponse {
	string redirectUri = 1;
}

message FinaliseAccountLinkingRequest {
	string service = 1;
	string state = 2;
	optional string issuer = 3;
	string code = 4;
	repeated string scopes = 5;
}

message FinaliseAccountLinkingResponse {
	string connectionId = 1;
}

message SupportedConnection {
	string service = 1;
	string displayName = 2;
	uint32 capabilities = 3;
}

message SupportedConnectionsResponse {
	repeated SupportedConnection availableConnections = 1;
}

message ConnectionsRequest {
    repeated string services = 1;
	optional uint32 capabilities = 2;
}

message Connection {
	string id = 1;
	string service = 2;
	optional string serviceUrl = 3;
	uint64 flags = 4;
	uint32 capabilities = 5;

	string userId = 6;
	optional string userName = 7;
	optional string emailAddress = 8;
}

message DeleteConnectionRequest {
	string connectionId = 1;
}

// todo: empty?
message DeleteConnectionResponse { }

message UpdateCapabilitiesRequest {
	string connectionId = 1;
	uint32 capabilities = 2;
}