<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <PackageReference Include="libphonenumber-csharp" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ReLiveWP.Identity\ReLiveWP.Identity.csproj" />
    <ProjectReference Include="..\ReLiveWP.ServiceDefaults\ReLiveWP.ServiceDefaults.csproj" />
    <ProjectReference Include="..\ReLiveWP.Grpc.Services\ReLiveWP.Grpc.Services.csproj" />
  </ItemGroup>
  
</Project>
