// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ReLiveWP.Backend.DeviceUpdate.Data;

#nullable disable

namespace ReLiveWP.Backend.DeviceUpdate.Data.Migrations
{
    [DbContext(typeof(UpdatesDbContext))]
    partial class UpdatesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ReLiveWP.Backend.DeviceUpdate.Model.AuthoredRevision", b =>
                {
                    b.Property<Guid>("UpdateId")
                        .HasColumnType("uuid");

                    b.Property<int>("RevisionNumber")
                        .HasColumnType("integer");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("RevisionId")
                        .HasColumnType("bigint");

                    b.HasKey("UpdateId", "RevisionNumber");

                    b.HasIndex("RevisionId")
                        .IsUnique();

                    b.ToTable("AuthoredRevisions");
                });

            modelBuilder.Entity("ReLiveWP.Backend.DeviceUpdate.Model.Update", b =>
                {
                    b.Property<long>("RevisionId")
                        .HasColumnType("bigint");

                    b.Property<string>("DeploymentAction")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsBundle")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsLeaf")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsLeafReported")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastChangeTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Origin")
                        .HasColumnType("integer");

                    b.Property<int>("RevisionNumber")
                        .HasColumnType("integer");

                    b.Property<Guid>("UpdateId")
                        .HasColumnType("uuid");

                    b.Property<int>("UpdateType")
                        .HasColumnType("integer");

                    b.HasKey("RevisionId");

                    b.HasIndex("UpdateId");

                    b.ToTable("Updates");
                });

            modelBuilder.Entity("ReLiveWP.Backend.DeviceUpdate.Model.UpdateBundle", b =>
                {
                    b.Property<long>("BundleRevisionId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("BundledUpdateId")
                        .HasColumnType("uuid");

                    b.Property<int?>("BundledRevisionNumber")
                        .HasColumnType("integer");

                    b.HasKey("BundleRevisionId", "BundledUpdateId");

                    b.HasIndex("BundledUpdateId");

                    b.ToTable("Bundles");
                });

            modelBuilder.Entity("ReLiveWP.Backend.DeviceUpdate.Model.UpdateDeployment", b =>
                {
                    b.Property<int>("Ring")
                        .HasColumnType("integer");

                    b.Property<Guid>("UpdateId")
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("LastChangeTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.HasKey("Ring", "UpdateId");

                    b.ToTable("Deployments");
                });

            modelBuilder.Entity("ReLiveWP.Backend.DeviceUpdate.Model.UpdateExtendedMetadata", b =>
                {
                    b.Property<long>("RevisionId")
                        .HasColumnType("bigint");

                    b.Property<string>("Xml")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("RevisionId");

                    b.ToTable("ExtendedMetadata");
                });

            modelBuilder.Entity("ReLiveWP.Backend.DeviceUpdate.Model.UpdateFile", b =>
                {
                    b.Property<long>("UpdateRevisionId")
                        .HasColumnType("bigint");

                    b.Property<string>("FileName")
                        .HasColumnType("text");

                    b.Property<string>("DigestSha1")
                        .HasColumnType("text");

                    b.Property<string>("DigestSha256")
                        .HasColumnType("text");

                    b.Property<string>("LocalPath")
                        .HasColumnType("text");

                    b.Property<DateTime?>("Modified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Size")
                        .HasColumnType("bigint");

                    b.Property<string>("SourceUrl")
                        .HasColumnType("text");

                    b.HasKey("UpdateRevisionId", "FileName");

                    b.ToTable("Files");
                });

            modelBuilder.Entity("ReLiveWP.Backend.DeviceUpdate.Model.UpdateFragment", b =>
                {
                    b.Property<long>("UpdateRevisionId")
                        .HasColumnType("bigint");

                    b.Property<int>("Ordinal")
                        .HasColumnType("integer");

                    b.Property<string>("FragmentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Xml")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UpdateRevisionId", "Ordinal");

                    b.ToTable("Fragments");
                });

            modelBuilder.Entity("ReLiveWP.Backend.DeviceUpdate.Model.UpdateLocalization", b =>
                {
                    b.Property<long>("UpdateRevisionId")
                        .HasColumnType("bigint");

                    b.Property<string>("Language")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("MoreInfoUrl")
                        .HasColumnType("text");

                    b.Property<string>("SupportUrl")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.HasKey("UpdateRevisionId", "Language");

                    b.ToTable("Localizations");
                });

            modelBuilder.Entity("ReLiveWP.Backend.DeviceUpdate.Model.UpdateMetadata", b =>
                {
                    b.Property<long>("RevisionId")
                        .HasColumnType("bigint");

                    b.Property<string>("SyncXml")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("RevisionId");

                    b.ToTable("Metadata");
                });

            modelBuilder.Entity("ReLiveWP.Backend.DeviceUpdate.Model.UpdatePrerequisite", b =>
                {
                    b.Property<long>("UpdateRevisionId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("PrerequisiteUpdateId")
                        .HasColumnType("uuid");

                    b.Property<int>("GroupId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsCategory")
                        .HasColumnType("boolean");

                    b.HasKey("UpdateRevisionId", "PrerequisiteUpdateId");

                    b.HasIndex("PrerequisiteUpdateId");

                    b.ToTable("Prerequisites");
                });

            modelBuilder.Entity("ReLiveWP.Backend.DeviceUpdate.Model.UpdateBundle", b =>
                {
                    b.HasOne("ReLiveWP.Backend.DeviceUpdate.Model.Update", "Bundle")
                        .WithMany("BundledUpdates")
                        .HasForeignKey("BundleRevisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bundle");
                });

            modelBuilder.Entity("ReLiveWP.Backend.DeviceUpdate.Model.UpdateExtendedMetadata", b =>
                {
                    b.HasOne("ReLiveWP.Backend.DeviceUpdate.Model.Update", "Update")
                        .WithOne("ExtendedMetadata")
                        .HasForeignKey("ReLiveWP.Backend.DeviceUpdate.Model.UpdateExtendedMetadata", "RevisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Update");
                });

            modelBuilder.Entity("ReLiveWP.Backend.DeviceUpdate.Model.UpdateFile", b =>
                {
                    b.HasOne("ReLiveWP.Backend.DeviceUpdate.Model.Update", "Update")
                        .WithMany("Files")
                        .HasForeignKey("UpdateRevisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Update");
                });

            modelBuilder.Entity("ReLiveWP.Backend.DeviceUpdate.Model.UpdateFragment", b =>
                {
                    b.HasOne("ReLiveWP.Backend.DeviceUpdate.Model.Update", "Update")
                        .WithMany("Fragments")
                        .HasForeignKey("UpdateRevisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Update");
                });

            modelBuilder.Entity("ReLiveWP.Backend.DeviceUpdate.Model.UpdateLocalization", b =>
                {
                    b.HasOne("ReLiveWP.Backend.DeviceUpdate.Model.Update", "Update")
                        .WithMany("Localizations")
                        .HasForeignKey("UpdateRevisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Update");
                });

            modelBuilder.Entity("ReLiveWP.Backend.DeviceUpdate.Model.UpdateMetadata", b =>
                {
                    b.HasOne("ReLiveWP.Backend.DeviceUpdate.Model.Update", "Update")
                        .WithOne("Metadata")
                        .HasForeignKey("ReLiveWP.Backend.DeviceUpdate.Model.UpdateMetadata", "RevisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Update");
                });

            modelBuilder.Entity("ReLiveWP.Backend.DeviceUpdate.Model.UpdatePrerequisite", b =>
                {
                    b.HasOne("ReLiveWP.Backend.DeviceUpdate.Model.Update", "Update")
                        .WithMany("Prerequisites")
                        .HasForeignKey("UpdateRevisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Update");
                });

            modelBuilder.Entity("ReLiveWP.Backend.DeviceUpdate.Model.Update", b =>
                {
                    b.Navigation("BundledUpdates");

                    b.Navigation("ExtendedMetadata");

                    b.Navigation("Files");

                    b.Navigation("Fragments");

                    b.Navigation("Localizations");

                    b.Navigation("Metadata");

                    b.Navigation("Prerequisites");
                });
#pragma warning restore 612, 618
        }
    }
}
