// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReLiveWP.Backend.Mailbox.Data;

#nullable disable

namespace ReLiveWP.Backend.Mailbox.Migrations
{
    [DbContext(typeof(MailboxDbContext))]
    partial class MailboxDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("ReLiveWP.Backend.Mailbox.Data.Entities.DbCalendarAttendee", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<byte?>("AttendeeStatus")
                        .HasColumnType("INTEGER");

                    b.Property<byte?>("AttendeeType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CalendarItemId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CalendarItemId");

                    b.ToTable("CalendarAttendees");
                });

            modelBuilder.Entity("ReLiveWP.Backend.Mailbox.Data.Entities.DbCalendarCategory", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("CalendarItemId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CalendarItemId");

                    b.ToTable("CalendarCategories");
                });

            modelBuilder.Entity("ReLiveWP.Backend.Mailbox.Data.Entities.DbCalendarException", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("AllDayEvent")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("AppointmentReplyTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("BodyLegacy")
                        .HasColumnType("TEXT");

                    b.Property<byte?>("BusyStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CalendarItemId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool?>("Deleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DtStamp")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExceptionStartTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("InstanceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .HasColumnType("TEXT");

                    b.Property<byte?>("MeetingStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("OnlineMeetingConfLink")
                        .HasColumnType("TEXT");

                    b.Property<string>("OnlineMeetingExternalLink")
                        .HasColumnType("TEXT");

                    b.Property<uint?>("Reminder")
                        .HasColumnType("INTEGER");

                    b.Property<uint?>("ResponseType")
                        .HasColumnType("INTEGER");

                    b.Property<byte?>("Sensitivity")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Subject")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CalendarItemId");

                    b.ToTable("CalendarExceptions");
                });

            modelBuilder.Entity("ReLiveWP.Backend.Mailbox.Data.Entities.DbCalendarExceptionAttendee", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<byte?>("AttendeeStatus")
                        .HasColumnType("INTEGER");

                    b.Property<byte?>("AttendeeType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CalendarExceptionId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CalendarExceptionId");

                    b.ToTable("CalendarExceptionAttendees");
                });

            modelBuilder.Entity("ReLiveWP.Backend.Mailbox.Data.Entities.DbCalendarExceptionCategory", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("CalendarExceptionId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CalendarExceptionId");

                    b.ToTable("CalendarExceptionCategories");
                });

            modelBuilder.Entity("ReLiveWP.Backend.Mailbox.Data.Entities.DbContactAnnotation", b =>
                {
                    b.Property<string>("ContactItemId")
                        .HasColumnType("TEXT");

                    b.Property<long?>("Cid")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContactType")
                        .HasColumnType("TEXT");

                    b.Property<int?>("FavoriteOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImMri")
                        .HasColumnType("TEXT");

                    b.Property<string>("ObjectId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TrustLevel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserTileHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserTileUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("WLId")
                        .HasColumnType("TEXT");

                    b.HasKey("ContactItemId");

                    b.ToTable("ContactAnnotations");
                });

            modelBuilder.Entity("ReLiveWP.Backend.Mailbox.Data.Entities.DbContactCategory", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactItemId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ContactItemId");

                    b.ToTable("ContactCategories");
                });

            modelBuilder.Entity("ReLiveWP.Backend.Mailbox.Data.Entities.DbContactChild", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactItemId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ContactItemId");

                    b.ToTable("ContactChildren");
                });

            modelBuilder.Entity("ReLiveWP.Backend.Mailbox.Data.Entities.DbDeviceInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("EnableOutboundSMS")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FriendlyName")
                        .HasColumnType("TEXT");

                    b.Property<string>("IMEI")
                        .HasColumnType("TEXT");

                    b.Property<string>("MobileOperator")
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .HasColumnType("TEXT");

                    b.Property<string>("OS")
                        .HasColumnType("TEXT");

                    b.Property<string>("OSLanguage")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserAgent")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "DeviceId")
                        .IsUnique();

                    b.ToTable("DeviceInfos");
                });

            modelBuilder.Entity("ReLiveWP.Backend.Mailbox.Data.Entities.DbFolder", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AccountName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ParentServerId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "Id")
                        .IsUnique();

                    b.ToTable("Folders");
                });

            modelBuilder.Entity("ReLiveWP.Backend.Mailbox.Data.Entities.DbFolderEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .HasColumnType("TEXT");

                    b.Property<int>("EventType")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FolderType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ParentServerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ServerId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Id");

                    b.ToTable("FolderEvents");
                });

            modelBuilder.Entity("ReLiveWP.Backend.Mailbox.Data.Entities.DbItem", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("CollectionId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemClass")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<string>("ServerId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CollectionId");

                    b.HasIndex("UserId", "CollectionId");

                    b.HasIndex("UserId", "CollectionId", "ServerId")
                        .IsUnique();

                    b.ToTable("Items");

                    b.HasDiscriminator<string>("ItemClass").HasValue("DbItem");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("ReLiveWP.Backend.Mailbox.Data.Entities.DbItemEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CollectionId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("EventType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ServerId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "CollectionId", "Id");

                    b.ToTable("ItemEvents");
                });

            modelBuilder.Entity("ReLiveWP.Backend.Mailbox.Data.Entities.DbSyncState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CachedAnnotationNames")
                        .HasColumnType("TEXT");

                    b.Property<string>("CollectionId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastSeenAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("SyncKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("Watermark")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "DeviceId", "CollectionId")
                        .IsUnique();

                    b.ToTable("SyncStates");
                });

            modelBuilder.Entity("ReLiveWP.Backend.Mailbox.Data.Entities.DbCalendar", b =>
                {
                    b.HasBaseType("ReLiveWP.Backend.Mailbox.Data.Entities.DbItem");

                    b.Property<bool?>("AllDayEvent")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("AppointmentReplyTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("BodyLegacy")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("BodyTruncated")
                        .HasColumnType("INTEGER");

                    b.Property<byte?>("BusyStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClientUid")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("DisallowNewTimeProposal")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DtStamp")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .HasColumnType("TEXT");

                    b.Property<byte?>("MeetingStatus")
                        .HasColumnType("INTEGER");

                    b.Property<byte?>("NativeBodyType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("OnlineMeetingConfLink")
                        .HasColumnType("TEXT");

                    b.Property<string>("OnlineMeetingExternalLink")
                        .HasColumnType("TEXT");

                    b.Property<string>("OrganizerEmail")
                        .HasColumnType("TEXT");

                    b.Property<string>("OrganizerName")
                        .HasColumnType("TEXT");

                    b.Property<byte?>("RecurrenceCalendarType")
                        .HasColumnType("INTEGER");

                    b.Property<byte?>("RecurrenceDayOfMonth")
                        .HasColumnType("INTEGER");

                    b.Property<ushort?>("RecurrenceDayOfWeek")
                        .HasColumnType("INTEGER");

                    b.Property<byte?>("RecurrenceFirstDayOfWeek")
                        .HasColumnType("INTEGER");

                    b.Property<ushort?>("RecurrenceInterval")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("RecurrenceIsLeapMonth")
                        .HasColumnType("INTEGER");

                    b.Property<byte?>("RecurrenceMonthOfYear")
                        .HasColumnType("INTEGER");

                    b.Property<ushort?>("RecurrenceOccurrences")
                        .HasColumnType("INTEGER");

                    b.Property<byte?>("RecurrenceType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("RecurrenceUntil")
                        .HasColumnType("TEXT");

                    b.Property<byte?>("RecurrenceWeekOfMonth")
                        .HasColumnType("INTEGER");

                    b.Property<uint?>("Reminder")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("ResponseRequested")
                        .HasColumnType("INTEGER");

                    b.Property<uint?>("ResponseType")
                        .HasColumnType("INTEGER");

                    b.Property<byte?>("Sensitivity")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Subject")
                        .HasColumnType("TEXT");

                    b.Property<string>("Timezone")
                        .HasColumnType("TEXT");

                    b.Property<string>("Uid")
                        .HasColumnType("TEXT");

                    b.ToTable("Items", t =>
                        {
                            t.Property("Notes")
                                .HasColumnName("DbCalendar_Notes");
                        });

                    b.HasDiscriminator().HasValue("Calendar");
                });

            modelBuilder.Entity("ReLiveWP.Backend.Mailbox.Data.Entities.DbContact", b =>
                {
                    b.HasBaseType("ReLiveWP.Backend.Mailbox.Data.Entities.DbItem");

                    b.Property<string>("AccountName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Alias")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Anniversary")
                        .HasColumnType("TEXT");

                    b.Property<string>("AssistantName")
                        .HasColumnType("TEXT");

                    b.Property<string>("AssistantPhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Birthday")
                        .HasColumnType("TEXT");

                    b.Property<string>("Business2PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("BusinessAddressCity")
                        .HasColumnType("TEXT");

                    b.Property<string>("BusinessAddressCountry")
                        .HasColumnType("TEXT");

                    b.Property<string>("BusinessAddressPostalCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("BusinessAddressState")
                        .HasColumnType("TEXT");

                    b.Property<string>("BusinessAddressStreet")
                        .HasColumnType("TEXT");

                    b.Property<string>("BusinessFaxNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("BusinessPhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("CarPhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyMainPhone")
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyName")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Department")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email1Address")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email2Address")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email3Address")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileAs")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("GovernmentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Home2PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("HomeAddressCity")
                        .HasColumnType("TEXT");

                    b.Property<string>("HomeAddressCountry")
                        .HasColumnType("TEXT");

                    b.Property<string>("HomeAddressPostalCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("HomeAddressState")
                        .HasColumnType("TEXT");

                    b.Property<string>("HomeAddressStreet")
                        .HasColumnType("TEXT");

                    b.Property<string>("HomeFaxNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("HomePhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("IMAddress")
                        .HasColumnType("TEXT");

                    b.Property<string>("IMAddress2")
                        .HasColumnType("TEXT");

                    b.Property<string>("IMAddress3")
                        .HasColumnType("TEXT");

                    b.Property<string>("JobTitle")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<string>("MMS")
                        .HasColumnType("TEXT");

                    b.Property<string>("ManagerName")
                        .HasColumnType("TEXT");

                    b.Property<string>("MiddleName")
                        .HasColumnType("TEXT");

                    b.Property<string>("MobilePhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("NickName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("OfficeLocation")
                        .HasColumnType("TEXT");

                    b.Property<string>("OtherAddressCity")
                        .HasColumnType("TEXT");

                    b.Property<string>("OtherAddressCountry")
                        .HasColumnType("TEXT");

                    b.Property<string>("OtherAddressPostalCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("OtherAddressState")
                        .HasColumnType("TEXT");

                    b.Property<string>("OtherAddressStreet")
                        .HasColumnType("TEXT");

                    b.Property<string>("PagerNumber")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Picture")
                        .HasColumnType("BLOB");

                    b.Property<string>("RadioPhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("Spouse")
                        .HasColumnType("TEXT");

                    b.Property<string>("Suffix")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<string>("WebPage")
                        .HasColumnType("TEXT");

                    b.Property<int?>("WeightedRank")
                        .HasColumnType("INTEGER");

                    b.Property<string>("YomiCompanyName")
                        .HasColumnType("TEXT");

                    b.Property<string>("YomiFirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("YomiLastName")
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("Contact");
                });

            modelBuilder.Entity("ReLiveWP.Backend.Mailbox.Data.Entities.DbEmail", b =>
                {
                    b.HasBaseType("ReLiveWP.Backend.Mailbox.Data.Entities.DbItem");

                    b.HasDiscriminator().HasValue("Email");
                });

            modelBuilder.Entity("ReLiveWP.Backend.Mailbox.Data.Entities.DbTask", b =>
                {
                    b.HasBaseType("ReLiveWP.Backend.Mailbox.Data.Entities.DbItem");

                    b.HasDiscriminator().HasValue("Task");
                });

            modelBuilder.Entity("ReLiveWP.Backend.Mailbox.Data.Entities.DbCalendarAttendee", b =>
                {
                    b.HasOne("ReLiveWP.Backend.Mailbox.Data.Entities.DbCalendar", "CalendarItem")
                        .WithMany("Attendees")
                        .HasForeignKey("CalendarItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CalendarItem");
                });

            modelBuilder.Entity("ReLiveWP.Backend.Mailbox.Data.Entities.DbCalendarCategory", b =>
                {
                    b.HasOne("ReLiveWP.Backend.Mailbox.Data.Entities.DbCalendar", "CalendarItem")
                        .WithMany("Categories")
                        .HasForeignKey("CalendarItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CalendarItem");
                });

            modelBuilder.Entity("ReLiveWP.Backend.Mailbox.Data.Entities.DbCalendarException", b =>
                {
                    b.HasOne("ReLiveWP.Backend.Mailbox.Data.Entities.DbCalendar", "CalendarItem")
                        .WithMany("Exceptions")
                        .HasForeignKey("CalendarItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CalendarItem");
                });

            modelBuilder.Entity("ReLiveWP.Backend.Mailbox.Data.Entities.DbCalendarExceptionAttendee", b =>
                {
                    b.HasOne("ReLiveWP.Backend.Mailbox.Data.Entities.DbCalendarException", "CalendarException")
                        .WithMany("Attendees")
                        .HasForeignKey("CalendarExceptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CalendarException");
                });

            modelBuilder.Entity("ReLiveWP.Backend.Mailbox.Data.Entities.DbCalendarExceptionCategory", b =>
                {
                    b.HasOne("ReLiveWP.Backend.Mailbox.Data.Entities.DbCalendarException", "CalendarException")
                        .WithMany("Categories")
                        .HasForeignKey("CalendarExceptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CalendarException");
                });

            modelBuilder.Entity("ReLiveWP.Backend.Mailbox.Data.Entities.DbContactAnnotation", b =>
                {
                    b.HasOne("ReLiveWP.Backend.Mailbox.Data.Entities.DbContact", "ContactItem")
                        .WithOne("Annotation")
                        .HasForeignKey("ReLiveWP.Backend.Mailbox.Data.Entities.DbContactAnnotation", "ContactItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContactItem");
                });

            modelBuilder.Entity("ReLiveWP.Backend.Mailbox.Data.Entities.DbContactCategory", b =>
                {
                    b.HasOne("ReLiveWP.Backend.Mailbox.Data.Entities.DbContact", "ContactItem")
                        .WithMany("Categories")
                        .HasForeignKey("ContactItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContactItem");
                });

            modelBuilder.Entity("ReLiveWP.Backend.Mailbox.Data.Entities.DbContactChild", b =>
                {
                    b.HasOne("ReLiveWP.Backend.Mailbox.Data.Entities.DbContact", "ContactItem")
                        .WithMany("Children")
                        .HasForeignKey("ContactItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContactItem");
                });

            modelBuilder.Entity("ReLiveWP.Backend.Mailbox.Data.Entities.DbItem", b =>
                {
                    b.HasOne("ReLiveWP.Backend.Mailbox.Data.Entities.DbFolder", "Collection")
                        .WithMany("FolderItems")
                        .HasForeignKey("CollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Collection");
                });

            modelBuilder.Entity("ReLiveWP.Backend.Mailbox.Data.Entities.DbCalendarException", b =>
                {
                    b.Navigation("Attendees");

                    b.Navigation("Categories");
                });

            modelBuilder.Entity("ReLiveWP.Backend.Mailbox.Data.Entities.DbFolder", b =>
                {
                    b.Navigation("FolderItems");
                });

            modelBuilder.Entity("ReLiveWP.Backend.Mailbox.Data.Entities.DbCalendar", b =>
                {
                    b.Navigation("Attendees");

                    b.Navigation("Categories");

                    b.Navigation("Exceptions");
                });

            modelBuilder.Entity("ReLiveWP.Backend.Mailbox.Data.Entities.DbContact", b =>
                {
                    b.Navigation("Annotation");

                    b.Navigation("Categories");

                    b.Navigation("Children");
                });
#pragma warning restore 612, 618
        }
    }
}
