<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <UserSecretsId>6cc4b98e-30b7-4216-85cd-65ac619f665a</UserSecretsId>
  </PropertyGroup>
  
  <ItemGroup>
    <PackageReference Include="Duende.IdentityModel.OidcClient" />
    <PackageReference Include="Google.Apis.Auth" />
    <PackageReference Include="Google.Apis.Oauth2.v2" />
    <PackageReference Include="Grpc.Tools">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Duende.IdentityModel.OidcClient.Extensions" />
    <PackageReference Include="FishyFlip" VersionOverride="3.11.0--no-branch-.1" />
    <PackageReference Include="Grpc.AspNetCore" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ReLiveWP.Identity\ReLiveWP.Identity.csproj" />
    <ProjectReference Include="..\ReLiveWP.ServiceDefaults\ReLiveWP.ServiceDefaults.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Protobuf Include="../protos/oauth.proto" GrpcServices="Server">
      <Link>Protos\oauth.proto</Link>
    </Protobuf>
  </ItemGroup>

</Project>
