// writes src/generated/**.g.ts from the committed spec/*.json. nothing else is needed, so a clean
// clone builds without the spec docs.
//
//   node tools/generate.mjs            write src/generated/
//   node tools/generate.mjs --check    exit 1 if regenerating would change anything

import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const pkgRoot = resolve(here, '..');
const SPEC = resolve(pkgRoot, 'spec');
const OUT = resolve(pkgRoot, 'src/generated');

const flag = (name) => process.argv.slice(2).includes(name);

function fail(message) {
    console.error(`generate: ${message}`);
    process.exit(2);
}

function spec(name) {
    try {
        return JSON.parse(readFileSync(resolve(SPEC, `${name}.json`), 'utf8'));
    } catch (e) {
        return fail(`cannot read spec/${name}.json: ${e.message}\n`
            + '          run `pnpm extract --docs <dir>` if you are refreshing from the specifications');
    }
}

// the schema says xs:dateTime for everything, the actual wire format isn't in there. this came
// off EasDateHelper.cs on the server.
const DATE_FORMAT = {
    Calendar: 'compact',
    Notes: 'compact',
    Contacts: 'extended',
    Contacts2: 'extended',
    Tasks: 'extended',
    Email: 'extended',
    Email2: 'extended',
    AirSyncBase: 'extended',
};

// what the transport speaks. a property none of these support can't reach the wire, so it's left
// out of the models. that's also what picks AirSyncBase:Body over the 2.5-only Email:Body, which
// would otherwise both want to be `body`.
const SUPPORTED = ['12.1', '14.0', '14.1'];

// ApplicationData carries the class's own properties plus the AirSyncBase ones
const MODELS = [
    { file: 'email', name: 'Email', class: 'Email', namespaces: ['Email', 'Email2', 'AirSyncBase'] },
    { file: 'contact', name: 'Contact', class: 'Contact', namespaces: ['Contacts', 'Contacts2', 'AirSyncBase'] },
    { file: 'calendar', name: 'Calendar', class: 'Calendar', namespaces: ['Calendar', 'AirSyncBase'] },
    { file: 'task', name: 'Task', class: 'Task', namespaces: ['Tasks', 'AirSyncBase'] },
    { file: 'note', name: 'Note', class: 'Note', namespaces: ['Notes', 'AirSyncBase'] },
];

const header = (what, source) =>
    `// GENERATED by tools/generate.mjs from ${source}. Run \`pnpm gen\` to update.\n`
    + `// ${what}. Do not edit.\n`;

function nameList(names) {
    const lines = [];
    let line = '   ';

    for (const name of names) {
        const piece = ` '${name}',`;
        if (line.length + piece.length > 100) { lines.push(line); line = '   '; }
        line += piece;
    }
    if (line.trim().length > 0) lines.push(line);

    return lines.length === 0 ? '' : `${lines.join('\n')}\n`;
}

function codepages(data) {
    const compact = data.pages.map((p) => ({ page: p.page, ns: p.ns, xmlns: p.xmlns, tokens: p.tokens }));

    const tables =
        header(`${data.pageCount} code pages, ${data.tokenCount} tokens`, 'spec/codepages.json') +
        '\n' +
        'export interface GeneratedCodePage {\n' +
        '    readonly page: number;\n' +
        '    readonly ns: string;\n' +
        '    readonly xmlns: string;\n' +
        '    readonly tokens: Readonly<Record<string, number>>;\n' +
        '}\n' +
        '\n' +
        'export const CODE_PAGES: readonly GeneratedCodePage[] = JSON.parse(\n' +
        `    ${JSON.stringify(JSON.stringify(compact))});\n`;

    const tags =
        header(`${data.pageCount} namespaces, ${data.tokenCount} tags`, 'spec/codepages.json') +
        '\n' +
        "import { makeTags } from '../nodes/tags.ts';\n" +
        '\n' +
        data.pages
            .map((p) => `export const ${p.ns} = makeTags('${p.ns}', [\n${nameList(Object.keys(p.tokens))}] as const);\n`)
            .join('\n');

    const gated = data.pages.reduce(
        (n, p) => n + Object.values(p.versions).filter((v) => v !== 'All').length, 0);

    const versions =
        header(`protocol versions per tag; ${gated} of ${data.tokenCount} are version-gated`, 'spec/codepages.json') +
        '\n' +
        "export const TAG_VERSIONS: Readonly<Record<string, Readonly<Record<string, 'All' | readonly string[]>>>> =\n" +
        `    JSON.parse(${JSON.stringify(JSON.stringify(
            Object.fromEntries(data.pages.map((p) => [p.ns, p.versions]))))});\n`;

    return [['codepages.g.ts', tables], ['tags.g.ts', tags], ['tag-versions.g.ts', versions]];
}

function status(data) {
    const keys = Object.keys(data.tables).sort();
    const total = keys.reduce((n, k) => n + data.tables[k].statuses.length, 0);

    const values = Object.fromEntries(keys.map((k) => {
        const { spec: from, section, statuses } = data.tables[k];
        return [k, { spec: from, section, values: statuses.map((s) => s.value) }];
    }));

    const text = Object.fromEntries(keys.map((k) => [
        k,
        Object.fromEntries(data.tables[k].statuses.map(({ value, meaning, name, scope }) => [
            value,
            { meaning, ...(name === undefined ? {} : { name }), ...(scope === undefined ? {} : { scope }) },
        ])),
    ]));

    const table =
        header(`${keys.length} tables, ${total} status codes`, 'spec/status.json') +
        '\n' +
        'export interface EasStatusTable {\n' +
        '    readonly spec: string;\n' +
        '    readonly section: string;\n' +
        '    readonly values: readonly number[];\n' +
        '}\n' +
        '\n' +
        'export type EasStatusTableName =\n' +
        `${keys.map((k) => `    | '${k}'`).join('\n')};\n` +
        '\n' +
        'export const EAS_STATUS: Readonly<Record<EasStatusTableName, EasStatusTable>> = JSON.parse(\n' +
        `    ${JSON.stringify(JSON.stringify(values))});\n`;

    // split from the values so a bundle can take the numbers without the prose
    const prose =
        header(`meanings for ${total} status codes, keyed by table then value`, 'spec/status.json') +
        '\n' +
        "import type { EasStatusTableName } from './status.g.ts';\n" +
        '\n' +
        'export interface EasStatusText {\n' +
        '    readonly meaning: string;\n' +
        '    readonly name?: string;\n' +
        '    readonly scope?: string;\n' +
        '}\n' +
        '\n' +
        'export const EAS_STATUS_TEXT:\n' +
        '    Readonly<Record<EasStatusTableName, Readonly<Record<string, EasStatusText>>>> = JSON.parse(\n' +
        `    ${JSON.stringify(JSON.stringify(text))});\n`;

    return [['status.g.ts', table], ['status-text.g.ts', prose]];
}

// MIMEData becomes mimeData, not mIMEData. trailing acronyms like InternetCPID stay as they are.
const camel = (name) => {
    const run = /^([A-Z]+)(?![a-z])/.exec(name)?.[1];
    if (run !== undefined && run.length > 1) return run.toLowerCase() + name.slice(run.length);
    return name.charAt(0).toLowerCase() + name.slice(1);
};

const TS = { node: 'EasNode', string: 'string', number: 'number', boolean: 'boolean', Date: 'Date', Uint8Array: 'Uint8Array' };

function model(spec, data, versions) {
    const fields = [];
    for (const ns of spec.namespaces) {
        const props = data.namespaces[ns];
        if (props === undefined) fail(`spec/items.json has no namespace ${ns}`);

        for (const prop of props) {
            const supported = versions[ns]?.[prop.name];
            if (Array.isArray(supported) && !supported.some((v) => SUPPORTED.includes(v))) continue;

            fields.push({ ...prop, ns, property: camel(prop.name), type: TS[prop.ts] });
        }
    }

    const seen = new Map();
    for (const field of fields) {
        const clash = seen.get(field.property);
        if (clash) fail(`${spec.name}: ${clash.ns}:${clash.name} and ${field.ns}:${field.name} both map to ${field.property}`);
        seen.set(field.property, field);
    }

    const namespaces = [...new Set(fields.map((f) => f.ns))];
    const reader = (f) => ({
        string: `text(node, ${f.ns}.${f.name})`,
        number: `int(node, ${f.ns}.${f.name})`,
        boolean: `tri(node, ${f.ns}.${f.name})`,
        Date: `readDate(text(node, ${f.ns}.${f.name}))`,
        Uint8Array: `bytes(node, ${f.ns}.${f.name})`,
        EasNode: `pick(node, ${f.ns}.${f.name})`,
    }[f.type]);
    const writer = (f) =>
        f.type === 'Date' ? `writeDate(item.${f.property}, '${DATE_FORMAT[f.ns]}')` : `item.${f.property}`;

    const body =
        header(`${fields.length} properties across ${namespaces.join(', ')}`, 'spec/items.json') +
        '\n' +
        "import { bytes, int, pick, text, tri } from '../../nodes/read.ts';\n" +
        "import { readDate, writeDate } from '../../nodes/dates.ts';\n" +
        "import { mergeProperties, type PropertySpec } from '../../nodes/merge.ts';\n" +
        "import type { EasChild, EasNode } from '../../nodes/node.ts';\n" +
        `import { ${namespaces.join(', ')} } from '../tags.g.ts';\n` +
        '\n' +
        `export interface ${spec.name}Item {\n` +
        `${fields.map((f) => `    ${f.property}?: ${f.type} | undefined;`).join('\n')}\n` +
        '}\n' +
        '\n' +
        `export const ${spec.file.toUpperCase()}_PROPERTIES: readonly PropertySpec[] = [\n` +
        `${fields.map((f) =>
            `    { property: '${f.property}', tag: ${f.ns}.${f.name}, kind: '${f.type}'`
            + (f.type === 'Date' ? `, dateFormat: '${DATE_FORMAT[f.ns]}'` : '')
            + ' },').join('\n')}\n` +
        '];\n' +
        '\n' +
        `export function read${spec.name}(node: EasNode): ${spec.name}Item {\n` +
        '    return {\n' +
        `${fields.map((f) => `        ${f.property}: ${reader(f)},`).join('\n')}\n` +
        '    };\n' +
        '}\n' +
        '\n' +
        `export function write${spec.name}(item: ${spec.name}Item): EasChild[] {\n` +
        '    return [\n' +
        `${fields.map((f) => `        item.${f.property} === undefined ? undefined : ${f.ns}.${f.name}(${writer(f)}),`)
            .join('\n')}\n` +
        '    ].filter((n): n is EasNode => n !== undefined);\n' +
        '}\n' +
        '\n' +
        `export function merge${spec.name}(original: EasNode, changes: Partial<${spec.name}Item>): EasNode {\n` +
        `    return mergeProperties(original, changes, ${spec.file.toUpperCase()}_PROPERTIES);\n` +
        '}\n';

    return [`model/${spec.file}.g.ts`, body, fields.length];
}

function modelBarrel() {
    const names = MODELS.map((m) => m.name);

    return header(`${MODELS.length} item classes`, 'spec/items.json') +
        '\n' +
        `${MODELS.map((m) =>
            `export { read${m.name}, write${m.name}, merge${m.name}, ${m.file.toUpperCase()}_PROPERTIES, `
            + `type ${m.name}Item } from './${m.file}.g.ts';`).join('\n')}\n` +
        '\n' +
        `${MODELS.map((m) => `import { read${m.name} } from './${m.file}.g.ts';`).join('\n')}\n` +
        "import type { EasNode } from '../../nodes/node.ts';\n" +
        `${MODELS.map((m) => `import type { ${m.name}Item } from './${m.file}.g.ts';`).join('\n')}\n` +
        '\n' +
        `export type ItemClass = ${MODELS.map((m) => `'${m.class}'`).join(' | ')};\n` +
        '\n' +
        'export type Item =\n' +
        `${MODELS.map((m) => `    | { class: '${m.class}'; ${m.file}: ${m.name}Item }`).join('\n')};\n` +
        '\n' +
        `export function readItem(node: EasNode, cls: ItemClass): Item {\n` +
        '    switch (cls) {\n' +
        `${MODELS.map((m) => `        case '${m.class}': return { class: cls, ${m.file}: read${m.name}(node) };`).join('\n')}\n` +
        '    }\n' +
        '}\n' +
        '\n' +
        `export const ITEM_CLASSES: readonly ItemClass[] = [${names.map((_, i) => `'${MODELS[i].class}'`).join(', ')}];\n`;
}

function barrel(files) {
    return header('re-exports every generated module', 'spec/*.json') +
        '\n' +
        `${files.map((f) => `export * from './${f}';`).join('\n')}\n`;
}

const codepageData = spec('codepages');
const statusData = spec('status');
const itemData = spec('items');

const tagVersions = Object.fromEntries(codepageData.pages.map((p) => [p.ns, p.versions]));

const outputs = [...codepages(codepageData), ...status(statusData)];

let propertyCount = 0;
for (const entry of MODELS) {
    const [file, body, count] = model(entry, itemData, tagVersions);
    outputs.push([file, body]);
    propertyCount += count;
}
outputs.push(['model/index.g.ts', modelBarrel()]);
outputs.push(['index.g.ts', barrel(['codepages.g.ts', 'tags.g.ts', 'tag-versions.g.ts', 'status.g.ts', 'status-text.g.ts'])]);

const rendered = outputs.map(([name, content]) => [resolve(OUT, name), content]);

if (flag('--check')) {
    const stale = rendered.filter(([file, content]) => {
        try { return readFileSync(file, 'utf8') !== content; } catch { return true; }
    });
    if (stale.length) {
        console.error(`generate: out of date, run \`pnpm gen\`:\n${stale.map(([f]) => `  ${f}`).join('\n')}`);
        process.exit(1);
    }
    console.log(`generate: up to date (${outputs.length} files)`);
    process.exit(0);
}

mkdirSync(resolve(OUT, 'model'), { recursive: true });
for (const [file, content] of rendered) writeFileSync(file, content);
console.log(`generate: ${outputs.length} files, ${codepageData.tokenCount} tags, `
    + `${MODELS.length} item classes, ${propertyCount} properties`);
