<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FishyFlip" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" />
    <PackageReference Include="MisskeySharp" />
    <PackageReference Include="Razor.Templating.Core" />
    <PackageReference Include="System.Linq.Async" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Libraries\Atom\Atom.csproj" />
    <ProjectReference Include="..\ReLiveWP.Identity\ReLiveWP.Identity.csproj" />
    <ProjectReference Include="..\ReLiveWP.ServiceDefaults\ReLiveWP.ServiceDefaults.csproj" />
    <ProjectReference Include="..\ReLiveWP.Grpc.Services\ReLiveWP.Grpc.Services.csproj" />
  </ItemGroup>

</Project>
