<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <InternalsVisibleTo Include="ReLiveWP.Backend.SkyDrive.Tests" />
  </ItemGroup>

  <ItemGroup>
    <Protobuf Include="../protos/skyphotos.proto" GrpcServices="Server">
      <Link>Protos\skyphotos.proto</Link>
    </Protobuf>
    <Protobuf Include="../protos/skydocs.proto" GrpcServices="Server">
      <Link>Protos\skydocs.proto</Link>
    </Protobuf>
    <Protobuf Include="../protos/oauth.proto" GrpcServices="Client">
      <Link>Protos\oauth.proto</Link>
    </Protobuf>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Grpc.AspNetCore" />
    <PackageReference Include="Grpc.Net.ClientFactory" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ReLiveWP.Identity\ReLiveWP.Identity.csproj" />
    <ProjectReference Include="..\ReLiveWP.ServiceDefaults\ReLiveWP.ServiceDefaults.csproj" />
    <ProjectReference Include="..\Libraries\Dav\Dav.csproj" />
  </ItemGroup>

</Project>
