// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReLiveWP.Backend.Skybox.Data;

#nullable disable

namespace ReLiveWP.Backend.Skybox.Migrations
{
    [DbContext(typeof(SkyDbContext))]
    partial class SkyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("ReLiveWP.Backend.Skybox.Data.SkyDevice", b =>
                {
                    b.Property<string>("DeviceGuid")
                        .HasColumnType("TEXT");

                    b.Property<int>("BatteryLevel")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("Capabilities")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClientVersion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<uint>("ColorAccent")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ColorTheme")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CommercializedMobileOperator")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FriendlyName")
                        .HasColumnType("TEXT");

                    b.Property<string>("IMSI")
                        .HasColumnType("TEXT");

                    b.Property<int>("LCID")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("MPNSEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Make")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxWorkingSet")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MobileOperator")
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .HasColumnType("TEXT");

                    b.Property<string>("OSVersion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PinLocked")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ScreenResolution")
                        .HasColumnType("TEXT");

                    b.Property<bool>("SendLocationEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SimId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("SimLocked")
                        .HasColumnType("INTEGER");

                    b.Property<long>("StorageRemaining")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TZ")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("DeviceGuid");

                    b.ToTable("Devices");
                });
#pragma warning restore 612, 618
        }
    }
}
