<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <InternalsVisibleTo Include="ReLiveWP.Backend.Chat.Tests" />
  </ItemGroup>

  <ItemGroup>
    <Protobuf Include="$(RepoRoot)protos/chat.proto" GrpcServices="Server">
      <Link>Protos\chat.proto</Link>
    </Protobuf>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Grpc.AspNetCore" />
    <PackageReference Include="Grpc.Net.ClientFactory" />
    <PackageReference Include="RedLock.net" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\libraries\ReLiveWP.ServiceDefaults\ReLiveWP.ServiceDefaults.csproj" />
    <ProjectReference Include="..\..\libraries\ReLiveWP.Grpc.Services\ReLiveWP.Grpc.Services.csproj" />
  </ItemGroup>

</Project>
