<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <!--me when i lie-->
  <ItemGroup>
    <ProjectCapability Include="AspireOrchestration" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ReLiveWP.Backend.DeviceRegistration\ReLiveWP.Backend.DeviceRegistration.csproj">
      <ReferenceOutputAssembly>false</ReferenceOutputAssembly>
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\ReLiveWP.Backend.DeviceUpdate\ReLiveWP.Backend.DeviceUpdate.csproj">
      <ReferenceOutputAssembly>false</ReferenceOutputAssembly>
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\ReLiveWP.Backend.ConnectedServices\ReLiveWP.Backend.ConnectedServices.csproj">
      <ReferenceOutputAssembly>false</ReferenceOutputAssembly>
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\ReLiveWP.Backend.Identity\ReLiveWP.Backend.Identity.csproj">
      <ReferenceOutputAssembly>false</ReferenceOutputAssembly>
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\ReLiveWP.Backend.Skybox\ReLiveWP.Backend.Skybox.csproj">
      <ReferenceOutputAssembly>false</ReferenceOutputAssembly>
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\ReLiveWP.Services.Activation\ReLiveWP.Services.Activation.csproj">
      <ReferenceOutputAssembly>false</ReferenceOutputAssembly>
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\ReLiveWP.Services.Activity\ReLiveWP.Services.Activity.csproj">
      <ReferenceOutputAssembly>false</ReferenceOutputAssembly>
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\ReLiveWP.Services.AddressBook\ReLiveWP.Services.AddressBook.csproj">
      <ReferenceOutputAssembly>false</ReferenceOutputAssembly>
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\ReLiveWP.Services.Devices\ReLiveWP.Services.Devices.csproj">
      <ReferenceOutputAssembly>false</ReferenceOutputAssembly>
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\ReLiveWP.Services.Exchange\ReLiveWP.Services.Exchange.csproj">
      <ReferenceOutputAssembly>false</ReferenceOutputAssembly>
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\ReLiveWP.Services.Login\ReLiveWP.Services.Login.csproj">
      <ReferenceOutputAssembly>false</ReferenceOutputAssembly>
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\ReLiveWP.Services.Orion\ReLiveWP.Services.Orion.csproj" />
    <ProjectReference Include="..\ReLiveWP.Services.Push\ReLiveWP.Services.Push.csproj">
      <ReferenceOutputAssembly>false</ReferenceOutputAssembly>
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\ReLiveWP.Services.FindMyPhone\ReLiveWP.Services.FindMyPhone.csproj">
      <ReferenceOutputAssembly>false</ReferenceOutputAssembly>
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\ReLiveWP.Zune.Catalog\ReLiveWP.Zune.Catalog.csproj">
      <ReferenceOutputAssembly>false</ReferenceOutputAssembly>
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\ReLiveWP.Zune.Commerce\ReLiveWP.Zune.Commerce.csproj">
      <ReferenceOutputAssembly>false</ReferenceOutputAssembly>
      <Private>false</Private>
    </ProjectReference>
  </ItemGroup>

</Project>
