<Project Sdk="Microsoft.NET.Sdk.Web">
  
  <ItemGroup>
    <InternalsVisibleTo Include="ReLiveWP.Backend.ClearingHouse.Tests" />
  </ItemGroup>

  <ItemGroup>
    <Protobuf Include="../protos/clearinghouse.proto" GrpcServices="Server">
      <Link>Protos\clearinghouse.proto</Link>
    </Protobuf>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FolkerKinzel.VCards" />
    <PackageReference Include="Grpc.AspNetCore" />
    <PackageReference Include="Grpc.Net.ClientFactory" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    <PackageReference Include="RedLock.net" />
    <PackageReference Include="SixLabors.ImageSharp" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ReLiveWP.Identity\ReLiveWP.Identity.csproj" />
    <ProjectReference Include="..\ReLiveWP.ServiceDefaults\ReLiveWP.ServiceDefaults.csproj" />
    <ProjectReference Include="..\ReLiveWP.Grpc.Services\ReLiveWP.Grpc.Services.csproj" />
  </ItemGroup>

</Project>
