// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ReLiveWP.Backend.Mailbox.Data;

#nullable disable

namespace ReLiveWP.Backend.Mailbox.Migrations
{
    [DbContext(typeof(MailboxDbContext))]
    [Migration("20260717184317_AddPerformanceIndexes")]
    partial class AddPerformanceIndexes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ReLiveWP.Backend.Mailbox.Data.Entities.DbAttachment", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<byte[]>("Content")
                        .HasColumnType("bytea");

                    b.Property<string>("ContentId")
                        .HasColumnType("text");

                    b.Property<string>("ContentLocation")
                        .HasColumnType("text");

                    b.Property<string>("ContentType")
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text");

                    b.Property<string>("EmailItemId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("EstimatedDataSize")
                        .HasColumnType("integer");

                    b.Property<bool?>("IsInline")
                        .HasColumnType("boolean");

                    b.Property<byte?>("Method")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("EmailItemId");

                    b.ToTable("Attachments");
                });

            modelBuilder.Entity("ReLiveWP.Backend.Mailbox.Data.Entities.DbCalendarAttendee", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<byte?>("AttendeeStatus")
                        .HasColumnType("smallint");

                    b.Property<byte?>("AttendeeType")
                        .HasColumnType("smallint");

                    b.Property<string>("CalendarItemId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CalendarItemId");

                    b.ToTable("CalendarAttendees");
                });

            modelBuilder.Entity("ReLiveWP.Backend.Mailbox.Data.Entities.DbCalendarCategory", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("CalendarItemId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CalendarItemId");

                    b.ToTable("CalendarCategories");
                });

            modelBuilder.Entity("ReLiveWP.Backend.Mailbox.Data.Entities.DbCalendarException", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<bool?>("AllDayEvent")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("AppointmentReplyTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("BodyLegacy")
                        .HasColumnType("text");

                    b.Property<byte?>("BusyStatus")
                        .HasColumnType("smallint");

                    b.Property<string>("CalendarItemId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool?>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("DtStamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExceptionStartTime")
                        .HasColumnType("text");

                    b.Property<string>("InstanceId")
                        .HasColumnType("text");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<byte?>("MeetingStatus")
                        .HasColumnType("smallint");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("OnlineMeetingConfLink")
                        .HasColumnType("text");

                    b.Property<string>("OnlineMeetingExternalLink")
                        .HasColumnType("text");

                    b.Property<long?>("Reminder")
                        .HasColumnType("bigint");

                    b.Property<long?>("ResponseType")
                        .HasColumnType("bigint");

                    b.Property<byte?>("Sensitivity")
                        .HasColumnType("smallint");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Subject")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CalendarItemId");

                    b.ToTable("CalendarExceptions");
                });

            modelBuilder.Entity("ReLiveWP.Backend.Mailbox.Data.Entities.DbCalendarExceptionAttendee", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<byte?>("AttendeeStatus")
                        .HasColumnType("smallint");

                    b.Property<byte?>("AttendeeType")
                        .HasColumnType("smallint");

                    b.Property<string>("CalendarExceptionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CalendarExceptionId");

                    b.ToTable("CalendarExceptionAttendees");
                });

            modelBuilder.Entity("ReLiveWP.Backend.Mailbox.Data.Entities.DbCalendarExceptionCategory", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("CalendarExceptionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CalendarExceptionId");

                    b.ToTable("CalendarExceptionCategories");
                });

            modelBuilder.Entity("ReLiveWP.Backend.Mailbox.Data.Entities.DbContactAnnotation", b =>
                {
                    b.Property<string>("ContactItemId")
                        .HasColumnType("text");

                    b.Property<long?>("Cid")
                        .HasColumnType("bigint");

                    b.Property<string>("ContactType")
                        .HasColumnType("text");

                    b.Property<int?>("FavoriteOrder")
                        .HasColumnType("integer");

                    b.Property<string>("ImMri")
                        .HasColumnType("text");

                    b.Property<string>("ObjectId")
                        .HasColumnType("text");

                    b.Property<int?>("TrustLevel")
                        .HasColumnType("integer");

                    b.Property<string>("UserTileHash")
                        .HasColumnType("text");

                    b.Property<string>("UserTileUrl")
                        .HasColumnType("text");

                    b.Property<string>("WLId")
                        .HasColumnType("text");

                    b.HasKey("ContactItemId");

                    b.HasIndex("Cid");

                    b.ToTable("ContactAnnotations");
                });

            modelBuilder.Entity("ReLiveWP.Backend.Mailbox.Data.Entities.DbContactCategory", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ContactItemId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ContactItemId");

                    b.ToTable("ContactCategories");
                });

            modelBuilder.Entity("ReLiveWP.Backend.Mailbox.Data.Entities.DbContactChild", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ContactItemId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ContactItemId");

                    b.ToTable("ContactChildren");
                });

            modelBuilder.Entity("ReLiveWP.Backend.Mailbox.Data.Entities.DbContactIdentity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<long>("ContactCid")
                        .HasColumnType("bigint");

                    b.Property<string>("ContactItemId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ContactItemId");

                    b.HasIndex("UserId", "ContactCid");

                    b.HasIndex("UserId", "Provider", "ExternalId")
                        .IsUnique();

                    b.ToTable("ContactIdentities");
                });

            modelBuilder.Entity("ReLiveWP.Backend.Mailbox.Data.Entities.DbDeviceInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("EnableOutboundSMS")
                        .HasColumnType("integer");

                    b.Property<string>("FriendlyName")
                        .HasColumnType("text");

                    b.Property<string>("IMEI")
                        .HasColumnType("text");

                    b.Property<string>("MobileOperator")
                        .HasColumnType("text");

                    b.Property<string>("Model")
                        .HasColumnType("text");

                    b.Property<string>("OS")
                        .HasColumnType("text");

                    b.Property<string>("OSLanguage")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "DeviceId")
                        .IsUnique();

                    b.ToTable("DeviceInfos");
                });

            modelBuilder.Entity("ReLiveWP.Backend.Mailbox.Data.Entities.DbFolder", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("AccountName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("boolean");

                    b.Property<string>("ParentServerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SourceId")
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "Id")
                        .IsUnique();

                    b.ToTable("Folders");
                });

            modelBuilder.Entity("ReLiveWP.Backend.Mailbox.Data.Entities.DbFolderEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("DisplayName")
                        .HasColumnType("text");

                    b.Property<int>("EventType")
                        .HasColumnType("integer");

                    b.Property<int?>("FolderType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ParentServerId")
                        .HasColumnType("text");

                    b.Property<string>("ServerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Id");

                    b.ToTable("FolderEvents");
                });

            modelBuilder.Entity("ReLiveWP.Backend.Mailbox.Data.Entities.DbItem", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ClientId")
                        .HasColumnType("text");

                    b.Property<string>("CollectionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ItemClass")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("ServerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ValidationFlaggedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ValidationReason")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CollectionId");

                    b.HasIndex("UserId", "CollectionId");

                    b.HasIndex("UserId", "ServerId");

                    b.HasIndex("UserId", "CollectionId", "ClientId")
                        .IsUnique()
                        .HasFilter("\"ClientId\" IS NOT NULL AND \"DeletedAt\" IS NULL");

                    b.HasIndex("UserId", "CollectionId", "ServerId")
                        .IsUnique();

                    b.ToTable("Items");

                    b.HasDiscriminator<string>("ItemClass").HasValue("DbItem");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("ReLiveWP.Backend.Mailbox.Data.Entities.DbItemEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CollectionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EventType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ServerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "CollectionId", "Id");

                    b.ToTable("ItemEvents");
                });

            modelBuilder.Entity("ReLiveWP.Backend.Mailbox.Data.Entities.DbNoteCategory", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NoteItemId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("NoteItemId");

                    b.ToTable("NoteCategories");
                });

            modelBuilder.Entity("ReLiveWP.Backend.Mailbox.Data.Entities.DbSyncState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CachedAnnotationNames")
                        .HasColumnType("text");

                    b.Property<string>("CollectionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PreviousSyncKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("PreviousWatermark")
                        .HasColumnType("bigint");

                    b.Property<string>("SyncKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("Watermark")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "DeviceId", "CollectionId")
                        .IsUnique();

                    b.ToTable("SyncStates");
                });

            modelBuilder.Entity("ReLiveWP.Backend.Mailbox.Data.Entities.DbCalendarItem", b =>
                {
                    b.HasBaseType("ReLiveWP.Backend.Mailbox.Data.Entities.DbItem");

                    b.Property<bool?>("AllDayEvent")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("AppointmentReplyTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("BodyLegacy")
                        .HasColumnType("text");

                    b.Property<bool?>("BodyTruncated")
                        .HasColumnType("boolean");

                    b.Property<byte?>("BusyStatus")
                        .HasColumnType("smallint");

                    b.Property<string>("ClientUid")
                        .HasColumnType("text");

                    b.Property<bool?>("DisallowNewTimeProposal")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("DtStamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<byte?>("MeetingStatus")
                        .HasColumnType("smallint");

                    b.Property<byte?>("NativeBodyType")
                        .HasColumnType("smallint");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("OnlineMeetingConfLink")
                        .HasColumnType("text");

                    b.Property<string>("OnlineMeetingExternalLink")
                        .HasColumnType("text");

                    b.Property<string>("OrganizerEmail")
                        .HasColumnType("text");

                    b.Property<string>("OrganizerName")
                        .HasColumnType("text");

                    b.Property<byte?>("RecurrenceCalendarType")
                        .HasColumnType("smallint");

                    b.Property<byte?>("RecurrenceDayOfMonth")
                        .HasColumnType("smallint");

                    b.Property<int?>("RecurrenceDayOfWeek")
                        .HasColumnType("integer");

                    b.Property<byte?>("RecurrenceFirstDayOfWeek")
                        .HasColumnType("smallint");

                    b.Property<int?>("RecurrenceInterval")
                        .HasColumnType("integer");

                    b.Property<bool?>("RecurrenceIsLeapMonth")
                        .HasColumnType("boolean");

                    b.Property<byte?>("RecurrenceMonthOfYear")
                        .HasColumnType("smallint");

                    b.Property<int?>("RecurrenceOccurrences")
                        .HasColumnType("integer");

                    b.Property<byte?>("RecurrenceType")
                        .HasColumnType("smallint");

                    b.Property<DateTime?>("RecurrenceUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte?>("RecurrenceWeekOfMonth")
                        .HasColumnType("smallint");

                    b.Property<long?>("Reminder")
                        .HasColumnType("bigint");

                    b.Property<bool?>("ResponseRequested")
                        .HasColumnType("boolean");

                    b.Property<long?>("ResponseType")
                        .HasColumnType("bigint");

                    b.Property<byte?>("Sensitivity")
                        .HasColumnType("smallint");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Subject")
                        .HasColumnType("text");

                    b.Property<string>("Timezone")
                        .HasColumnType("text");

                    b.Property<string>("Uid")
                        .HasColumnType("text");

                    b.ToTable("Items", t =>
                        {
                            t.Property("Notes")
                                .HasColumnName("DbCalendarItem_Notes");
                        });

                    b.HasDiscriminator().HasValue("Calendar");
                });

            modelBuilder.Entity("ReLiveWP.Backend.Mailbox.Data.Entities.DbContactItem", b =>
                {
                    b.HasBaseType("ReLiveWP.Backend.Mailbox.Data.Entities.DbItem");

                    b.Property<string>("AccountName")
                        .HasColumnType("text");

                    b.Property<string>("Alias")
                        .HasColumnType("text");

                    b.Property<DateTime?>("Anniversary")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AssistantName")
                        .HasColumnType("text");

                    b.Property<string>("AssistantPhoneNumber")
                        .HasColumnType("text");

                    b.Property<DateTime?>("Birthday")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Business2PhoneNumber")
                        .HasColumnType("text");

                    b.Property<string>("BusinessAddressCity")
                        .HasColumnType("text");

                    b.Property<string>("BusinessAddressCountry")
                        .HasColumnType("text");

                    b.Property<string>("BusinessAddressPostalCode")
                        .HasColumnType("text");

                    b.Property<string>("BusinessAddressState")
                        .HasColumnType("text");

                    b.Property<string>("BusinessAddressStreet")
                        .HasColumnType("text");

                    b.Property<string>("BusinessFaxNumber")
                        .HasColumnType("text");

                    b.Property<string>("BusinessPhoneNumber")
                        .HasColumnType("text");

                    b.Property<string>("CarPhoneNumber")
                        .HasColumnType("text");

                    b.Property<string>("CompanyMainPhone")
                        .HasColumnType("text");

                    b.Property<string>("CompanyName")
                        .HasColumnType("text");

                    b.Property<string>("CustomerId")
                        .HasColumnType("text");

                    b.Property<string>("Department")
                        .HasColumnType("text");

                    b.Property<string>("Email1Address")
                        .HasColumnType("text");

                    b.Property<string>("Email2Address")
                        .HasColumnType("text");

                    b.Property<string>("Email3Address")
                        .HasColumnType("text");

                    b.Property<string>("FileAs")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<string>("GovernmentId")
                        .HasColumnType("text");

                    b.Property<string>("Home2PhoneNumber")
                        .HasColumnType("text");

                    b.Property<string>("HomeAddressCity")
                        .HasColumnType("text");

                    b.Property<string>("HomeAddressCountry")
                        .HasColumnType("text");

                    b.Property<string>("HomeAddressPostalCode")
                        .HasColumnType("text");

                    b.Property<string>("HomeAddressState")
                        .HasColumnType("text");

                    b.Property<string>("HomeAddressStreet")
                        .HasColumnType("text");

                    b.Property<string>("HomeFaxNumber")
                        .HasColumnType("text");

                    b.Property<string>("HomePhoneNumber")
                        .HasColumnType("text");

                    b.Property<string>("IMAddress")
                        .HasColumnType("text");

                    b.Property<string>("IMAddress2")
                        .HasColumnType("text");

                    b.Property<string>("IMAddress3")
                        .HasColumnType("text");

                    b.Property<string>("JobTitle")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<string>("MMS")
                        .HasColumnType("text");

                    b.Property<string>("ManagerName")
                        .HasColumnType("text");

                    b.Property<string>("MiddleName")
                        .HasColumnType("text");

                    b.Property<string>("MobilePhoneNumber")
                        .HasColumnType("text");

                    b.Property<string>("NickName")
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("OfficeLocation")
                        .HasColumnType("text");

                    b.Property<string>("OtherAddressCity")
                        .HasColumnType("text");

                    b.Property<string>("OtherAddressCountry")
                        .HasColumnType("text");

                    b.Property<string>("OtherAddressPostalCode")
                        .HasColumnType("text");

                    b.Property<string>("OtherAddressState")
                        .HasColumnType("text");

                    b.Property<string>("OtherAddressStreet")
                        .HasColumnType("text");

                    b.Property<string>("PagerNumber")
                        .HasColumnType("text");

                    b.Property<byte[]>("Picture")
                        .HasColumnType("bytea");

                    b.Property<string>("RadioPhoneNumber")
                        .HasColumnType("text");

                    b.Property<string>("Spouse")
                        .HasColumnType("text");

                    b.Property<string>("Suffix")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<string>("WebPage")
                        .HasColumnType("text");

                    b.Property<int?>("WeightedRank")
                        .HasColumnType("integer");

                    b.Property<string>("YomiCompanyName")
                        .HasColumnType("text");

                    b.Property<string>("YomiFirstName")
                        .HasColumnType("text");

                    b.Property<string>("YomiLastName")
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("Contact");
                });

            modelBuilder.Entity("ReLiveWP.Backend.Mailbox.Data.Entities.DbEmail", b =>
                {
                    b.HasBaseType("ReLiveWP.Backend.Mailbox.Data.Entities.DbItem");

                    b.Property<string>("Bcc")
                        .HasColumnType("text");

                    b.Property<string>("Body")
                        .HasColumnType("text");

                    b.Property<byte?>("BodyType")
                        .HasColumnType("smallint");

                    b.Property<string>("Cc")
                        .HasColumnType("text");

                    b.Property<string>("ContentClass")
                        .HasColumnType("text");

                    b.Property<byte[]>("ConversationId")
                        .HasColumnType("bytea");

                    b.Property<byte[]>("ConversationIndex")
                        .HasColumnType("bytea");

                    b.Property<DateTime?>("DateReceived")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayTo")
                        .HasColumnType("text");

                    b.Property<DateTime?>("FlagCompleteTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FlagDateCompleted")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FlagDueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool?>("FlagReminderSet")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("FlagReminderTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FlagStartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte?>("FlagStatus")
                        .HasColumnType("smallint");

                    b.Property<string>("FlagSubject")
                        .HasColumnType("text");

                    b.Property<string>("FlagType")
                        .HasColumnType("text");

                    b.Property<DateTime?>("FlagUtcDueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FlagUtcStartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("From")
                        .HasColumnType("text");

                    b.Property<byte?>("Importance")
                        .HasColumnType("smallint");

                    b.Property<string>("InternetCPID")
                        .HasColumnType("text");

                    b.Property<int?>("LastVerbExecuted")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LastVerbExecutionTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MessageClass")
                        .HasColumnType("text");

                    b.Property<string>("MimeRaw")
                        .HasColumnType("text");

                    b.Property<byte?>("NativeBodyType")
                        .HasColumnType("smallint")
                        .HasColumnName("Email_NativeBodyType");

                    b.Property<bool?>("Read")
                        .HasColumnType("boolean");

                    b.Property<string>("ReplyTo")
                        .HasColumnType("text");

                    b.Property<string>("Sender")
                        .HasColumnType("text");

                    b.Property<string>("Subject")
                        .HasColumnType("text")
                        .HasColumnName("Email_Subject");

                    b.Property<string>("ThreadTopic")
                        .HasColumnType("text");

                    b.Property<string>("To")
                        .HasColumnType("text");

                    b.HasIndex("UserId", "ConversationId");

                    b.HasDiscriminator().HasValue("Email");
                });

            modelBuilder.Entity("ReLiveWP.Backend.Mailbox.Data.Entities.DbNote", b =>
                {
                    b.HasBaseType("ReLiveWP.Backend.Mailbox.Data.Entities.DbItem");

                    b.Property<string>("Body")
                        .HasColumnType("text")
                        .HasColumnName("Note_Body");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Note_LastModifiedDate");

                    b.Property<string>("MessageClass")
                        .HasColumnType("text")
                        .HasColumnName("Note_MessageClass");

                    b.Property<byte?>("NativeBodyType")
                        .HasColumnType("smallint")
                        .HasColumnName("Note_NativeBodyType");

                    b.Property<string>("Subject")
                        .HasColumnType("text")
                        .HasColumnName("Note_Subject");

                    b.HasDiscriminator().HasValue("Note");
                });

            modelBuilder.Entity("ReLiveWP.Backend.Mailbox.Data.Entities.DbTask", b =>
                {
                    b.HasBaseType("ReLiveWP.Backend.Mailbox.Data.Entities.DbItem");

                    b.Property<bool?>("Complete")
                        .HasColumnType("boolean")
                        .HasColumnName("Task_Complete");

                    b.Property<DateTime?>("DateCompleted")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Task_DateCompleted");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Task_DueDate");

                    b.Property<byte?>("Importance")
                        .HasColumnType("smallint")
                        .HasColumnName("Task_Importance");

                    b.Property<byte?>("NativeBodyType")
                        .HasColumnType("smallint")
                        .HasColumnName("Task_NativeBodyType");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("Task_Notes");

                    b.Property<byte?>("RecurrenceCalendarType")
                        .HasColumnType("smallint")
                        .HasColumnName("Task_RecurrenceCalendarType");

                    b.Property<byte?>("RecurrenceDayOfMonth")
                        .HasColumnType("smallint")
                        .HasColumnName("Task_RecurrenceDayOfMonth");

                    b.Property<byte?>("RecurrenceDayOfWeek")
                        .HasColumnType("smallint")
                        .HasColumnName("Task_RecurrenceDayOfWeek");

                    b.Property<byte?>("RecurrenceDeadOccur")
                        .HasColumnType("smallint")
                        .HasColumnName("Task_RecurrenceDeadOccur");

                    b.Property<byte?>("RecurrenceFirstDayOfWeek")
                        .HasColumnType("smallint")
                        .HasColumnName("Task_RecurrenceFirstDayOfWeek");

                    b.Property<int?>("RecurrenceInterval")
                        .HasColumnType("integer")
                        .HasColumnName("Task_RecurrenceInterval");

                    b.Property<bool?>("RecurrenceIsLeapMonth")
                        .HasColumnType("boolean")
                        .HasColumnName("Task_RecurrenceIsLeapMonth");

                    b.Property<byte?>("RecurrenceMonthOfYear")
                        .HasColumnType("smallint")
                        .HasColumnName("Task_RecurrenceMonthOfYear");

                    b.Property<byte?>("RecurrenceOccurrences")
                        .HasColumnType("smallint")
                        .HasColumnName("Task_RecurrenceOccurrences");

                    b.Property<bool?>("RecurrenceRegenerate")
                        .HasColumnType("boolean")
                        .HasColumnName("Task_RecurrenceRegenerate");

                    b.Property<DateTime?>("RecurrenceStart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Task_RecurrenceStart");

                    b.Property<byte?>("RecurrenceType")
                        .HasColumnType("smallint")
                        .HasColumnName("Task_RecurrenceType");

                    b.Property<DateTime?>("RecurrenceUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Task_RecurrenceUntil");

                    b.Property<byte?>("RecurrenceWeekOfMonth")
                        .HasColumnType("smallint")
                        .HasColumnName("Task_RecurrenceWeekOfMonth");

                    b.Property<bool?>("ReminderSet")
                        .HasColumnType("boolean")
                        .HasColumnName("Task_ReminderSet");

                    b.Property<DateTime?>("ReminderTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Task_ReminderTime");

                    b.Property<byte?>("Sensitivity")
                        .HasColumnType("smallint")
                        .HasColumnName("Task_Sensitivity");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Task_StartDate");

                    b.Property<string>("Subject")
                        .HasColumnType("text")
                        .HasColumnName("Task_Subject");

                    b.Property<DateTime?>("UtcDueDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Task_UtcDueDate");

                    b.Property<DateTime?>("UtcStartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Task_UtcStartDate");

                    b.HasDiscriminator().HasValue("Task");
                });

            modelBuilder.Entity("ReLiveWP.Backend.Mailbox.Data.Entities.DbAttachment", b =>
                {
                    b.HasOne("ReLiveWP.Backend.Mailbox.Data.Entities.DbEmail", "EmailItem")
                        .WithMany("Attachments")
                        .HasForeignKey("EmailItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EmailItem");
                });

            modelBuilder.Entity("ReLiveWP.Backend.Mailbox.Data.Entities.DbCalendarAttendee", b =>
                {
                    b.HasOne("ReLiveWP.Backend.Mailbox.Data.Entities.DbCalendarItem", "CalendarItem")
                        .WithMany("Attendees")
                        .HasForeignKey("CalendarItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CalendarItem");
                });

            modelBuilder.Entity("ReLiveWP.Backend.Mailbox.Data.Entities.DbCalendarCategory", b =>
                {
                    b.HasOne("ReLiveWP.Backend.Mailbox.Data.Entities.DbCalendarItem", "CalendarItem")
                        .WithMany("Categories")
                        .HasForeignKey("CalendarItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CalendarItem");
                });

            modelBuilder.Entity("ReLiveWP.Backend.Mailbox.Data.Entities.DbCalendarException", b =>
                {
                    b.HasOne("ReLiveWP.Backend.Mailbox.Data.Entities.DbCalendarItem", "CalendarItem")
                        .WithMany("Exceptions")
                        .HasForeignKey("CalendarItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CalendarItem");
                });

            modelBuilder.Entity("ReLiveWP.Backend.Mailbox.Data.Entities.DbCalendarExceptionAttendee", b =>
                {
                    b.HasOne("ReLiveWP.Backend.Mailbox.Data.Entities.DbCalendarException", "CalendarException")
                        .WithMany("Attendees")
                        .HasForeignKey("CalendarExceptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CalendarException");
                });

            modelBuilder.Entity("ReLiveWP.Backend.Mailbox.Data.Entities.DbCalendarExceptionCategory", b =>
                {
                    b.HasOne("ReLiveWP.Backend.Mailbox.Data.Entities.DbCalendarException", "CalendarException")
                        .WithMany("Categories")
                        .HasForeignKey("CalendarExceptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CalendarException");
                });

            modelBuilder.Entity("ReLiveWP.Backend.Mailbox.Data.Entities.DbContactAnnotation", b =>
                {
                    b.HasOne("ReLiveWP.Backend.Mailbox.Data.Entities.DbContactItem", "ContactItem")
                        .WithOne("Annotation")
                        .HasForeignKey("ReLiveWP.Backend.Mailbox.Data.Entities.DbContactAnnotation", "ContactItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContactItem");
                });

            modelBuilder.Entity("ReLiveWP.Backend.Mailbox.Data.Entities.DbContactCategory", b =>
                {
                    b.HasOne("ReLiveWP.Backend.Mailbox.Data.Entities.DbContactItem", "ContactItem")
                        .WithMany("Categories")
                        .HasForeignKey("ContactItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContactItem");
                });

            modelBuilder.Entity("ReLiveWP.Backend.Mailbox.Data.Entities.DbContactChild", b =>
                {
                    b.HasOne("ReLiveWP.Backend.Mailbox.Data.Entities.DbContactItem", "ContactItem")
                        .WithMany("Children")
                        .HasForeignKey("ContactItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContactItem");
                });

            modelBuilder.Entity("ReLiveWP.Backend.Mailbox.Data.Entities.DbContactIdentity", b =>
                {
                    b.HasOne("ReLiveWP.Backend.Mailbox.Data.Entities.DbContactItem", "ContactItem")
                        .WithMany()
                        .HasForeignKey("ContactItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContactItem");
                });

            modelBuilder.Entity("ReLiveWP.Backend.Mailbox.Data.Entities.DbItem", b =>
                {
                    b.HasOne("ReLiveWP.Backend.Mailbox.Data.Entities.DbFolder", "Collection")
                        .WithMany("FolderItems")
                        .HasForeignKey("CollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Collection");
                });

            modelBuilder.Entity("ReLiveWP.Backend.Mailbox.Data.Entities.DbNoteCategory", b =>
                {
                    b.HasOne("ReLiveWP.Backend.Mailbox.Data.Entities.DbNote", "NoteItem")
                        .WithMany("Categories")
                        .HasForeignKey("NoteItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NoteItem");
                });

            modelBuilder.Entity("ReLiveWP.Backend.Mailbox.Data.Entities.DbCalendarException", b =>
                {
                    b.Navigation("Attendees");

                    b.Navigation("Categories");
                });

            modelBuilder.Entity("ReLiveWP.Backend.Mailbox.Data.Entities.DbFolder", b =>
                {
                    b.Navigation("FolderItems");
                });

            modelBuilder.Entity("ReLiveWP.Backend.Mailbox.Data.Entities.DbCalendarItem", b =>
                {
                    b.Navigation("Attendees");

                    b.Navigation("Categories");

                    b.Navigation("Exceptions");
                });

            modelBuilder.Entity("ReLiveWP.Backend.Mailbox.Data.Entities.DbContactItem", b =>
                {
                    b.Navigation("Annotation");

                    b.Navigation("Categories");

                    b.Navigation("Children");
                });

            modelBuilder.Entity("ReLiveWP.Backend.Mailbox.Data.Entities.DbEmail", b =>
                {
                    b.Navigation("Attachments");
                });

            modelBuilder.Entity("ReLiveWP.Backend.Mailbox.Data.Entities.DbNote", b =>
                {
                    b.Navigation("Categories");
                });
#pragma warning restore 612, 618
        }
    }
}
