<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="ReLiveWP.Services.Activity.Tests" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AngleSharp" />
    <PackageReference Include="FishyFlip" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" />
    <PackageReference Include="Razor.Templating.Core" />
    <PackageReference Include="Google.Protobuf" />
    <PackageReference Include="Grpc.Net.Client" />
    <PackageReference Include="Grpc.Net.ClientFactory" />
    <PackageReference Include="Grpc.Tools">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\libraries\Atom\Atom.csproj" />
    <ProjectReference Include="..\..\libraries\ReLiveWP.Identity\ReLiveWP.Identity.csproj" />
    <ProjectReference Include="..\..\libraries\ReLiveWP.ServiceDefaults\ReLiveWP.ServiceDefaults.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Protobuf Include="$(RepoRoot)protos/authentication.proto" GrpcServices="Client">
      <Link>Protos\authentication.proto</Link>
    </Protobuf>
    <Protobuf Include="$(RepoRoot)protos/user.proto" GrpcServices="Client">
      <Link>Protos\user.proto</Link>
    </Protobuf>
    <Protobuf Include="$(RepoRoot)protos/oauth.proto" GrpcServices="Client">
      <Link>Protos\oauth.proto</Link>
    </Protobuf>
    <Protobuf Include="$(RepoRoot)protos/skyphotos.proto" GrpcServices="Client">
      <Link>Protos\skyphotos.proto</Link>
    </Protobuf>
    <Protobuf Include="$(RepoRoot)protos/mailbox_store.proto" GrpcServices="Client">
      <Link>Protos\mailbox_store.proto</Link>
    </Protobuf>
  </ItemGroup>

</Project>
