// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ReLiveWP.Backend.ClearingHouse.Data;

#nullable disable

namespace ReLiveWP.Backend.ClearingHouse.Migrations
{
    [DbContext(typeof(ClearingHouseDbContext))]
    [Migration("20260823163204_SharedSyncSources")]
    partial class SharedSyncSources
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ReLiveWP.Backend.ClearingHouse.Data.DbSyncSource", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConnectionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ConsecutiveFailures")
                        .HasColumnType("integer");

                    b.Property<string>("DeltaToken")
                        .HasColumnType("text");

                    b.Property<string>("FolderId")
                        .HasColumnType("text");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastAttemptedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastFailure")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastFailureAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LastRunCreated")
                        .HasColumnType("integer");

                    b.Property<int>("LastRunDeleted")
                        .HasColumnType("integer");

                    b.Property<int>("LastRunSkipped")
                        .HasColumnType("integer");

                    b.Property<int>("LastRunUpdated")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LastSyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RemoteDisplayName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RunRequestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("RunStartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ServiceId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("SyncEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SyncEnabled");

                    b.HasIndex("UserId", "ConnectionId", "Kind", "SourceId")
                        .IsUnique();

                    b.ToTable("SyncSources");
                });
#pragma warning restore 612, 618
        }
    }
}
