<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <InternalsVisibleTo Include="ReLiveWP.Backend.Mail.Tests" />
  </ItemGroup>

  <ItemGroup>
    <Protobuf Include="$(RepoRoot)protos/mail.proto" GrpcServices="Server">
      <Link>Protos\mail.proto</Link>
    </Protobuf>
    <Protobuf Include="$(RepoRoot)protos/user.proto" GrpcServices="Client">
      <Link>Protos\user.proto</Link>
    </Protobuf>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Grpc.AspNetCore" />
    <PackageReference Include="Grpc.Net.ClientFactory" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\libraries\ReLiveWP.Identity\ReLiveWP.Identity.csproj" />
    <ProjectReference Include="..\..\libraries\ReLiveWP.ServiceDefaults\ReLiveWP.ServiceDefaults.csproj" />
    <ProjectReference Include="..\..\libraries\ReLiveWP.Mail\ReLiveWP.Mail.csproj" />
  </ItemGroup>

</Project>
