// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ReLiveWP.Backend.Skybox.Data;

#nullable disable

namespace ReLiveWP.Backend.Skybox.Migrations
{
    [DbContext(typeof(SkyDbContext))]
    partial class SkyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ReLiveWP.Backend.Skybox.Data.SkyDevice", b =>
                {
                    b.Property<string>("DeviceGuid")
                        .HasColumnType("text");

                    b.Property<int>("BatteryLevel")
                        .HasColumnType("integer");

                    b.Property<long>("Capabilities")
                        .HasColumnType("bigint");

                    b.Property<string>("ClientVersion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("ColorAccent")
                        .HasColumnType("bigint");

                    b.Property<int>("ColorTheme")
                        .HasColumnType("integer");

                    b.Property<string>("CommercializedMobileOperator")
                        .HasColumnType("text");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("FriendlyName")
                        .HasColumnType("text");

                    b.Property<string>("IMSI")
                        .HasColumnType("text");

                    b.Property<int>("LCID")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("LastSeen")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("MPNSEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Make")
                        .HasColumnType("text");

                    b.Property<int>("MaxWorkingSet")
                        .HasColumnType("integer");

                    b.Property<string>("MobileOperator")
                        .HasColumnType("text");

                    b.Property<string>("Model")
                        .HasColumnType("text");

                    b.Property<string>("NotificationChannelUrl")
                        .HasColumnType("text");

                    b.Property<string>("OSVersion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PinLocked")
                        .HasColumnType("boolean");

                    b.Property<string>("ScreenResolution")
                        .HasColumnType("text");

                    b.Property<bool>("SendLocationEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("SimId")
                        .HasColumnType("text");

                    b.Property<bool>("SimLocked")
                        .HasColumnType("boolean");

                    b.Property<long>("StorageRemaining")
                        .HasColumnType("bigint");

                    b.Property<string>("TZ")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("DeviceGuid");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("ReLiveWP.Backend.Skybox.Data.SkyDevice", b =>
                {
                    b.OwnsOne("ReLiveWP.Backend.Skybox.Data.SkyDeviceLocation", "LastLocation", b1 =>
                        {
                            b1.Property<string>("SkyDeviceDeviceGuid")
                                .HasColumnType("text");

                            b1.Property<double>("Altitude")
                                .HasColumnType("double precision");

                            b1.Property<double>("Latitude")
                                .HasColumnType("double precision");

                            b1.Property<double>("Longitude")
                                .HasColumnType("double precision");

                            b1.Property<DateTimeOffset>("Reported")
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("SkyDeviceDeviceGuid");

                            b1.ToTable("Devices");

                            b1.WithOwner()
                                .HasForeignKey("SkyDeviceDeviceGuid");
                        });

                    b.Navigation("LastLocation");
                });
#pragma warning restore 612, 618
        }
    }
}
