// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReLiveWP.Backend.DeviceRegistration.Database;

#nullable disable

namespace ReLiveWP.Backend.DeviceRegistration.Migrations
{
    [DbContext(typeof(DevicesDbContext))]
    [Migration("20250809005045_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("ReLiveWP.Backend.DeviceRegistration.Model.DeviceModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("CertificateSubject")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IMEI")
                        .HasColumnType("TEXT");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .HasColumnType("TEXT");

                    b.Property<string>("OSVersion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Operator")
                        .HasColumnType("TEXT");

                    b.Property<string>("UniqueId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CertificateSubject");

                    b.HasIndex("UniqueId");

                    b.ToTable("Devices");
                });
#pragma warning restore 612, 618
        }
    }
}
